// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capability is one thing a person can call from the Capabilities panel.
 */
export class Capability {
    /**
     * Owner is "rig" for rig's own verbs, else the program's id.
     */
    "owner": string;
    "id": string;
    "title": string;
    "summary": string;
    "description": string;
    "returns": string;

    /**
     * Effects is "read-only", "destructive", a program's declared effect,
     * "changes state" for a rig verb that is neither, or empty when nothing
     * was declared. Anything but read-only is confirmed before it is sent.
     */
    "effects": string;

    /**
     * Args is the JSON Schema of the arguments, as JSON text; "" for none.
     */
    "args": string;

    /** Creates a new Capability instance. */
    constructor($$source: Partial<Capability> = {}) {
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("returns" in $$source)) {
            this["returns"] = "";
        }
        if (!("effects" in $$source)) {
            this["effects"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capability instance from a string or object.
     */
    static createFrom($$source: any = {}): Capability {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capability($$parsedSource as Partial<Capability>);
    }
}

/**
 * Card is one card on the board, as rig.panel.list answers it.
 */
export class Card {
    "id": string;
    "version": number;
    "from": string;
    "project": string;
    "title": string;
    "status": string;
    "severity": string;
    "body": string;

    /**
     * Progress is 0 to 1; HasProgress says whether there is any.
     */
    "progress": number;
    "hasProgress": boolean;
    "busy": boolean;
    "facts": Fact[];
    "actions": string[];
    "closed": boolean;
    "created": string;
    "updated": string;

    /** Creates a new Card instance. */
    constructor($$source: Partial<Card> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("from" in $$source)) {
            this["from"] = "";
        }
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("hasProgress" in $$source)) {
            this["hasProgress"] = false;
        }
        if (!("busy" in $$source)) {
            this["busy"] = false;
        }
        if (!("facts" in $$source)) {
            this["facts"] = [];
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }
        if (!("closed" in $$source)) {
            this["closed"] = false;
        }
        if (!("created" in $$source)) {
            this["created"] = "";
        }
        if (!("updated" in $$source)) {
            this["updated"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Card instance from a string or object.
     */
    static createFrom($$source: any = {}): Card {
        const $$createField11_0 = $$createType1;
        const $$createField12_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("facts" in $$parsedSource) {
            $$parsedSource["facts"] = $$createField11_0($$parsedSource["facts"]);
        }
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField12_0($$parsedSource["actions"]);
        }
        return new Card($$parsedSource as Partial<Card>);
    }
}

/**
 * CardList is the board: every open card and those closed in the last day,
 * newest change first, and how many rig left out past its cap.
 */
export class CardList {
    "cards": Card[];
    "omitted": number;

    /**
     * Missing is set when the daemon has no board yet, an older rigd.
     */
    "missing": boolean;

    /** Creates a new CardList instance. */
    constructor($$source: Partial<CardList> = {}) {
        if (!("cards" in $$source)) {
            this["cards"] = [];
        }
        if (!("omitted" in $$source)) {
            this["omitted"] = 0;
        }
        if (!("missing" in $$source)) {
            this["missing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CardList instance from a string or object.
     */
    static createFrom($$source: any = {}): CardList {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("cards" in $$parsedSource) {
            $$parsedSource["cards"] = $$createField0_0($$parsedSource["cards"]);
        }
        return new CardList($$parsedSource as Partial<CardList>);
    }
}

/**
 * Command is one declared command as the card lists it, and as the
 * Capabilities panel calls it.
 */
export class Command {
    "id": string;
    "title": string;
    "summary": string;
    "description": string;
    "effects": string;
    "returns": string;

    /**
     * Args is the declared JSON Schema as text, "" when none was declared.
     */
    "args": string;

    /** Creates a new Command instance. */
    constructor($$source: Partial<Command> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            this["summary"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("effects" in $$source)) {
            this["effects"] = "";
        }
        if (!("returns" in $$source)) {
            this["returns"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Command instance from a string or object.
     */
    static createFrom($$source: any = {}): Command {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Command($$parsedSource as Partial<Command>);
    }
}

/**
 * Deployment is what is actually RUNNING, artefact by artefact, and whether the
 * artefacts agree with each other.
 * 
 * ⛔ IT EXISTS BECAUSE `make install` REPORTED SUCCESS OVER A WINDOW IT DOES NOT
 * TOUCH, AND NOBODY COULD SEE IT FOR THIRTEEN HOURS (B89). The Makefile's
 * install/install-window split is deliberate and right; the consequence nobody
 * accounted for is that a person who deploys and then looks at the window has
 * deployed the daemon and is looking at something else. Telling a stale window
 * from a current one took four separate commands and a screenshot's footer.
 * 
 * ⛔ SO THE PANEL OWES THIS BEFORE IT OWES A BUTTON. Boris asked for a
 * management panel and said "redeployment should be trivial and automatic"
 * (plan/11, B90). Two buttons would have produced B89 again, because somebody
 * still has to know to press the second one. A redeploy control that cannot say
 * what is currently running is a button that reports success over the same
 * failure.
 * 
 * WHAT IT DOES NOT DO: it does not compare against the SOURCE TREE. An installed
 * window has no tree to read, and a "built" column derived from one would be
 * absent on exactly the machine that needs it. This compares the artefacts that
 * are running to each other, which is the comparison B89 actually needed.
 */
export class Deployment {
    /**
     * WindowVersion and its siblings are this binary's own ldflags stamp.
     */
    "windowVersion": string;
    "windowCommit": string;
    "windowBuilt": string;

    /**
     * DaemonVersion comes over the socket from the daemon that is answering
     * right now, never from a file on disk.
     */
    "daemonVersion": string;
    "daemonWire": string;
    "windowWire": string;
    "epoch": number;

    /**
     * Reached is false when the daemon did not answer. ⛔ IT IS NOT A SKEW:
     * "these disagree" and "I could not ask" are different facts and a panel
     * that renders them the same way is the B89 defect in a new place.
     */
    "reached": boolean;

    /**
     * Agree is only meaningful when Reached. Verdict says why in a person's
     * words, and it is the line the panel leads with.
     */
    "agree": boolean;
    "verdict": string;

    /** Creates a new Deployment instance. */
    constructor($$source: Partial<Deployment> = {}) {
        if (!("windowVersion" in $$source)) {
            this["windowVersion"] = "";
        }
        if (!("windowCommit" in $$source)) {
            this["windowCommit"] = "";
        }
        if (!("windowBuilt" in $$source)) {
            this["windowBuilt"] = "";
        }
        if (!("daemonVersion" in $$source)) {
            this["daemonVersion"] = "";
        }
        if (!("daemonWire" in $$source)) {
            this["daemonWire"] = "";
        }
        if (!("windowWire" in $$source)) {
            this["windowWire"] = "";
        }
        if (!("epoch" in $$source)) {
            this["epoch"] = 0;
        }
        if (!("reached" in $$source)) {
            this["reached"] = false;
        }
        if (!("agree" in $$source)) {
            this["agree"] = false;
        }
        if (!("verdict" in $$source)) {
            this["verdict"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Deployment instance from a string or object.
     */
    static createFrom($$source: any = {}): Deployment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Deployment($$parsedSource as Partial<Deployment>);
    }
}

/**
 * Fact is one label and value on a card.
 */
export class Fact {
    "label": string;
    "value": string;

    /** Creates a new Fact instance. */
    constructor($$source: Partial<Fact> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Fact instance from a string or object.
     */
    static createFrom($$source: any = {}): Fact {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Fact($$parsedSource as Partial<Fact>);
    }
}

/**
 * Guideline is one dated rule.
 */
export class Guideline {
    "id": string;
    "date": string;
    "who": string;
    "built": boolean;
    "title": string;
    "body": string;
    "cite": string;

    /** Creates a new Guideline instance. */
    constructor($$source: Partial<Guideline> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("who" in $$source)) {
            this["who"] = "";
        }
        if (!("built" in $$source)) {
            this["built"] = false;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("cite" in $$source)) {
            this["cite"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Guideline instance from a string or object.
     */
    static createFrom($$source: any = {}): Guideline {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Guideline($$parsedSource as Partial<Guideline>);
    }
}

/**
 * Guidelines is the whole answer.
 */
export class Guidelines {
    "revision": string;
    "rules": Guideline[];
    "programs": ProgramBuild[];

    /** Creates a new Guidelines instance. */
    constructor($$source: Partial<Guidelines> = {}) {
        if (!("revision" in $$source)) {
            this["revision"] = "";
        }
        if (!("rules" in $$source)) {
            this["rules"] = [];
        }
        if (!("programs" in $$source)) {
            this["programs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Guidelines instance from a string or object.
     */
    static createFrom($$source: any = {}): Guidelines {
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rules" in $$parsedSource) {
            $$parsedSource["rules"] = $$createField1_0($$parsedSource["rules"]);
        }
        if ("programs" in $$parsedSource) {
            $$parsedSource["programs"] = $$createField2_0($$parsedSource["programs"]);
        }
        return new Guidelines($$parsedSource as Partial<Guidelines>);
    }
}

/**
 * Health is what the status strip renders.
 * 
 * Detached is section 5g's fourth state: the window is up and the daemon is
 * not. The strip has to be able to say that, because a rail with no programs
 * in it looks identical to a rail whose daemon died.
 */
export class Health {
    "connected": boolean;
    "socket": string;
    "detail": string;
    "programs": number;

    /** Creates a new Health instance. */
    constructor($$source: Partial<Health> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("socket" in $$source)) {
            this["socket"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("programs" in $$source)) {
            this["programs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     */
    static createFrom($$source: any = {}): Health {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Health($$parsedSource as Partial<Health>);
    }
}

/**
 * Note is one notification, and its answer when it has one.
 */
export class Note {
    "id": string;
    "severity": string;
    "title": string;
    "body": string;
    "sender": string;

    /**
     * At is RFC 3339, the moment rig filed it.
     */
    "at": string;
    "suppressed": boolean;

    /**
     * Replies are the options it offered; ReplyText says it takes free text.
     */
    "replies": string[];
    "replyText": boolean;
    "asks": boolean;

    /**
     * Waiting is true while the program is still waiting for the answer.
     * An ask with no answer whose question rig no longer holds (the daemon
     * restarted since) is not waiting, and Forgotten says so.
     */
    "waiting": boolean;
    "forgotten": boolean;
    "answer": Reply | null;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("sender" in $$source)) {
            this["sender"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = "";
        }
        if (!("suppressed" in $$source)) {
            this["suppressed"] = false;
        }
        if (!("replies" in $$source)) {
            this["replies"] = [];
        }
        if (!("replyText" in $$source)) {
            this["replyText"] = false;
        }
        if (!("asks" in $$source)) {
            this["asks"] = false;
        }
        if (!("waiting" in $$source)) {
            this["waiting"] = false;
        }
        if (!("forgotten" in $$source)) {
            this["forgotten"] = false;
        }
        if (!("answer" in $$source)) {
            this["answer"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        const $$createField7_0 = $$createType2;
        const $$createField12_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("replies" in $$parsedSource) {
            $$parsedSource["replies"] = $$createField7_0($$parsedSource["replies"]);
        }
        if ("answer" in $$parsedSource) {
            $$parsedSource["answer"] = $$createField12_0($$parsedSource["answer"]);
        }
        return new Note($$parsedSource as Partial<Note>);
    }
}

/**
 * NoteList is the panel's whole answer.
 */
export class NoteList {
    "notes": Note[];

    /**
     * KeepDays is the age in force, and KeepFrom where it came from:
     * a config layer, or "default".
     */
    "keepDays": number;
    "keepFrom": string;

    /**
     * Evicted counts the notifications older than KeepDays. They stay in
     * the record; only the panel lets them go.
     */
    "evicted": number;

    /** Creates a new NoteList instance. */
    constructor($$source: Partial<NoteList> = {}) {
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }
        if (!("keepDays" in $$source)) {
            this["keepDays"] = 0;
        }
        if (!("keepFrom" in $$source)) {
            this["keepFrom"] = "";
        }
        if (!("evicted" in $$source)) {
            this["evicted"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NoteList instance from a string or object.
     */
    static createFrom($$source: any = {}): NoteList {
        const $$createField0_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField0_0($$parsedSource["notes"]);
        }
        return new NoteList($$parsedSource as Partial<NoteList>);
    }
}

/**
 * Program is one registered program, flattened for the rail.
 * 
 * Deliberately NOT here: an identity hue. Section 11 gives a program one
 * ownable hue and says a program without one leaves the shell achromatic, but
 * rigv1.Identity carries id, name, version, icon and description and no hue at
 * all - so every program is achromatic today, and not by choice. Deriving one
 * from the id would fake a declaration the program never made. It is the first
 * field the shell found missing from section 5e; the wire is not this session's
 * to change.
 */
export class Program {
    "id": string;
    "name": string;
    "version": string;
    "icon": string;
    "description": string;
    "coverage": string;
    "coverageNote": string;
    "services": string[];
    "hosted": boolean;
    "commands": number;

    /**
     * Where the program serves its own HTML, empty if it serves none.
     * Section 11's three tiers turn on this one field: empty means rig draws
     * the pane from what was declared, and a value means the program draws it.
     * rig refuses anything but a loopback origin at registration, so by the
     * time a value reaches here it has already been checked.
     */
    "paneUrl": string;

    /**
     * What the program card shows (plan/55, requirement 42), all of it from
     * the same rig.programs answer, so the card costs no new verb. Load is
     * "resident", "on call" or empty for a program that never said. AtRest,
     * Down and Stale are section 54's three reasons the listing is a kept
     * declaration rather than a live one.
     */
    "load": string;
    "atRest": boolean;
    "down": boolean;
    "stale": boolean;
    "events": string[];
    "commandList": Command[];

    /** Creates a new Program instance. */
    constructor($$source: Partial<Program> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("coverage" in $$source)) {
            this["coverage"] = "";
        }
        if (!("coverageNote" in $$source)) {
            this["coverageNote"] = "";
        }
        if (!("services" in $$source)) {
            this["services"] = [];
        }
        if (!("hosted" in $$source)) {
            this["hosted"] = false;
        }
        if (!("commands" in $$source)) {
            this["commands"] = 0;
        }
        if (!("paneUrl" in $$source)) {
            this["paneUrl"] = "";
        }
        if (!("load" in $$source)) {
            this["load"] = "";
        }
        if (!("atRest" in $$source)) {
            this["atRest"] = false;
        }
        if (!("down" in $$source)) {
            this["down"] = false;
        }
        if (!("stale" in $$source)) {
            this["stale"] = false;
        }
        if (!("events" in $$source)) {
            this["events"] = [];
        }
        if (!("commandList" in $$source)) {
            this["commandList"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Program instance from a string or object.
     */
    static createFrom($$source: any = {}): Program {
        const $$createField7_0 = $$createType2;
        const $$createField15_0 = $$createType2;
        const $$createField16_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField7_0($$parsedSource["services"]);
        }
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField15_0($$parsedSource["events"]);
        }
        if ("commandList" in $$parsedSource) {
            $$parsedSource["commandList"] = $$createField16_0($$parsedSource["commandList"]);
        }
        return new Program($$parsedSource as Partial<Program>);
    }
}

/**
 * ProgramBuild is when one program's binary was built.
 */
export class ProgramBuild {
    "program": string;

    /**
     * Day is the commit's local date, YYYY-MM-DD, the unit a rule is dated
     * in; "" when unknown.
     */
    "day": string;
    "commitTime": string;
    "modified": boolean;
    "unknownBecause": string;

    /** Creates a new ProgramBuild instance. */
    constructor($$source: Partial<ProgramBuild> = {}) {
        if (!("program" in $$source)) {
            this["program"] = "";
        }
        if (!("day" in $$source)) {
            this["day"] = "";
        }
        if (!("commitTime" in $$source)) {
            this["commitTime"] = "";
        }
        if (!("modified" in $$source)) {
            this["modified"] = false;
        }
        if (!("unknownBecause" in $$source)) {
            this["unknownBecause"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProgramBuild instance from a string or object.
     */
    static createFrom($$source: any = {}): ProgramBuild {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProgramBuild($$parsedSource as Partial<ProgramBuild>);
    }
}

/**
 * Reply is how a notification was answered.
 */
export class Reply {
    "reply": string;
    "text": string;
    "dismissed": boolean;
    "by": string;
    "at": string;

    /** Creates a new Reply instance. */
    constructor($$source: Partial<Reply> = {}) {
        if (!("reply" in $$source)) {
            this["reply"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("dismissed" in $$source)) {
            this["dismissed"] = false;
        }
        if (!("by" in $$source)) {
            this["by"] = "";
        }
        if (!("at" in $$source)) {
            this["at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Reply instance from a string or object.
     */
    static createFrom($$source: any = {}): Reply {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Reply($$parsedSource as Partial<Reply>);
    }
}

/**
 * Running is what the estate card says a supervised program is doing,
 * read from rig.health (section 11: the cards must be useful and
 * informative, Boris 2026-09-27). A program Rig does not supervise has no
 * row, and the card says so rather than inventing a state for it.
 */
export class Running {
    "id": string;

    /**
     * State is supervision's own word: starting, healthy, backoff, and
     * the rest. Since is when it entered that state, in unix milliseconds,
     * so the page can say "for 2 h" without a clock of its own.
     */
    "state": string;
    "since": number;
    "restarts": number;

    /**
     * Waiting and Parked are what the program last reported it is blocked
     * on, in its own words. Parked is the question a person has to answer.
     */
    "waiting": string;
    "parked": string;
    "lastExit": string;

    /** Creates a new Running instance. */
    constructor($$source: Partial<Running> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("since" in $$source)) {
            this["since"] = 0;
        }
        if (!("restarts" in $$source)) {
            this["restarts"] = 0;
        }
        if (!("waiting" in $$source)) {
            this["waiting"] = "";
        }
        if (!("parked" in $$source)) {
            this["parked"] = "";
        }
        if (!("lastExit" in $$source)) {
            this["lastExit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Running instance from a string or object.
     */
    static createFrom($$source: any = {}): Running {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Running($$parsedSource as Partial<Running>);
    }
}

/**
 * TryResult is what came back from one call, said as rig said it.
 */
export class TryResult {
    "ok": boolean;
    "text": string;

    /**
     * Call is the request as it went on the wire, so the panel can show
     * exactly what was sent.
     */
    "call": string;

    /** Creates a new TryResult instance. */
    constructor($$source: Partial<TryResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("call" in $$source)) {
            this["call"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): TryResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TryResult($$parsedSource as Partial<TryResult>);
    }
}

// Private type creation functions
const $$createType0 = Fact.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = Card.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Guideline.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ProgramBuild.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = Reply.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = Note.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = Command.createFrom;
const $$createType14 = $Create.Array($$createType13);
