// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Deployment is what is actually RUNNING, artefact by artefact, and whether the
 * artefacts agree with each other.
 * 
 * ⛔ IT EXISTS BECAUSE `make install` REPORTED SUCCESS OVER A WINDOW IT DOES NOT
 * TOUCH, AND NOBODY COULD SEE IT FOR THIRTEEN HOURS (B89). The Makefile's
 * install/install-window split is deliberate and right; the consequence nobody
 * accounted for is that a person who deploys and then looks at the window has
 * deployed the daemon and is looking at something else. Telling a stale window
 * from a current one took four separate commands and a screenshot's footer.
 * 
 * ⛔ SO THE PANEL OWES THIS BEFORE IT OWES A BUTTON. Boris asked for a
 * management panel and said "redeployment should be trivial and automatic"
 * (plan/11, B90). Two buttons would have produced B89 again, because somebody
 * still has to know to press the second one. A redeploy control that cannot say
 * what is currently running is a button that reports success over the same
 * failure.
 * 
 * WHAT IT DOES NOT DO: it does not compare against the SOURCE TREE. An installed
 * window has no tree to read, and a "built" column derived from one would be
 * absent on exactly the machine that needs it. This compares the artefacts that
 * are running to each other, which is the comparison B89 actually needed.
 */
export class Deployment {
    /**
     * WindowVersion and its siblings are this binary's own ldflags stamp.
     */
    "windowVersion": string;
    "windowCommit": string;
    "windowBuilt": string;

    /**
     * DaemonVersion comes over the socket from the daemon that is answering
     * right now, never from a file on disk.
     */
    "daemonVersion": string;
    "daemonWire": string;
    "windowWire": string;
    "epoch": number;

    /**
     * Reached is false when the daemon did not answer. ⛔ IT IS NOT A SKEW:
     * "these disagree" and "I could not ask" are different facts and a panel
     * that renders them the same way is the B89 defect in a new place.
     */
    "reached": boolean;

    /**
     * Agree is only meaningful when Reached. Verdict says why in a person's
     * words, and it is the line the panel leads with.
     */
    "agree": boolean;
    "verdict": string;

    /** Creates a new Deployment instance. */
    constructor($$source: Partial<Deployment> = {}) {
        if (!("windowVersion" in $$source)) {
            this["windowVersion"] = "";
        }
        if (!("windowCommit" in $$source)) {
            this["windowCommit"] = "";
        }
        if (!("windowBuilt" in $$source)) {
            this["windowBuilt"] = "";
        }
        if (!("daemonVersion" in $$source)) {
            this["daemonVersion"] = "";
        }
        if (!("daemonWire" in $$source)) {
            this["daemonWire"] = "";
        }
        if (!("windowWire" in $$source)) {
            this["windowWire"] = "";
        }
        if (!("epoch" in $$source)) {
            this["epoch"] = 0;
        }
        if (!("reached" in $$source)) {
            this["reached"] = false;
        }
        if (!("agree" in $$source)) {
            this["agree"] = false;
        }
        if (!("verdict" in $$source)) {
            this["verdict"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Deployment instance from a string or object.
     */
    static createFrom($$source: any = {}): Deployment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Deployment($$parsedSource as Partial<Deployment>);
    }
}

/**
 * Health is what the status strip renders.
 * 
 * Detached is section 5g's fourth state: the window is up and the daemon is
 * not. The strip has to be able to say that, because a rail with no programs
 * in it looks identical to a rail whose daemon died.
 */
export class Health {
    "connected": boolean;
    "socket": string;
    "detail": string;
    "programs": number;

    /** Creates a new Health instance. */
    constructor($$source: Partial<Health> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("socket" in $$source)) {
            this["socket"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("programs" in $$source)) {
            this["programs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     */
    static createFrom($$source: any = {}): Health {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Health($$parsedSource as Partial<Health>);
    }
}

/**
 * Program is one registered program, flattened for the rail.
 * 
 * Deliberately NOT here: an identity hue. Section 11 gives a program one
 * ownable hue and says a program without one leaves the shell achromatic, but
 * rigv1.Identity carries id, name, version, icon and description and no hue at
 * all - so every program is achromatic today, and not by choice. Deriving one
 * from the id would fake a declaration the program never made. It is the first
 * field the shell found missing from section 5e; the wire is not this session's
 * to change.
 */
export class Program {
    "id": string;
    "name": string;
    "version": string;
    "icon": string;
    "description": string;
    "coverage": string;
    "coverageNote": string;
    "services": string[];
    "hosted": boolean;
    "commands": number;

    /**
     * Where the program serves its own HTML, empty if it serves none.
     * Section 11's three tiers turn on this one field: empty means rig draws
     * the pane from what was declared, and a value means the program draws it.
     * rig refuses anything but a loopback origin at registration, so by the
     * time a value reaches here it has already been checked.
     */
    "paneUrl": string;

    /** Creates a new Program instance. */
    constructor($$source: Partial<Program> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("coverage" in $$source)) {
            this["coverage"] = "";
        }
        if (!("coverageNote" in $$source)) {
            this["coverageNote"] = "";
        }
        if (!("services" in $$source)) {
            this["services"] = [];
        }
        if (!("hosted" in $$source)) {
            this["hosted"] = false;
        }
        if (!("commands" in $$source)) {
            this["commands"] = 0;
        }
        if (!("paneUrl" in $$source)) {
            this["paneUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Program instance from a string or object.
     */
    static createFrom($$source: any = {}): Program {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField7_0($$parsedSource["services"]);
        }
        return new Program($$parsedSource as Partial<Program>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
