// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RigService is the window's only route to the daemon.
 * 
 * It dials per call rather than holding a connection, which is what makes
 * section 11's "the window survives a daemon restart" true for free: there is
 * no socket to go stale, and the next repaint reconnects. Section 22's split
 * pays for it - a unix socket dial is microseconds, and the alternative is
 * reconnect logic that M6 is going to write properly anyway.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Answer replies to a notification that asks: one of its options, free
 * text, or a dismissal. The daemon records the person at this screen as the
 * one who answered, and the program that asked is told.
 */
export function Answer(id: string, reply: string, text: string, dismissed: boolean): $CancellablePromise<$models.Reply> {
    return $Call.ByID(3036344461, id, reply, text, dismissed).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Board reads the board.
 */
export function Board(): $CancellablePromise<$models.CardList> {
    return $Call.ByID(1169951761).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Build is the four versions the binary carries, so the strip can show which
 * window is running without a person going to a terminal.
 */
export function Build(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1191479857).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Capabilities lists rig's verbs from the daemon and every registered
 * program's declared commands from the registry, rig first, each group in
 * the order its source gave it.
 */
export function Capabilities(): $CancellablePromise<$models.Capability[]> {
    return $Call.ByID(3599441113).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * Deployment never returns an error, for Health's reason: not reaching rig is a
 * state to draw, not a failure to handle.
 */
export function Deployment(): $CancellablePromise<$models.Deployment> {
    return $Call.ByID(69816036).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Guidelines reads rig.guidelines.
 */
export function Guidelines(): $CancellablePromise<$models.Guidelines> {
    return $Call.ByID(346564824).then(($result: any) => {
        return $$createType6($result);
    });
}

/**
 * Health never returns an error: not reaching rig is a state the strip draws,
 * not a failure the window has to handle.
 */
export function Health(): $CancellablePromise<$models.Health> {
    return $Call.ByID(2625630141).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * Notifications reads the panel's notifications.
 */
export function Notifications(): $CancellablePromise<$models.NoteList> {
    return $Call.ByID(3607183061).then(($result: any) => {
        return $$createType8($result);
    });
}

/**
 * Press sends one of a card's buttons to its owner. The presser is this
 * window's connection, which rig names.
 */
export function Press(card: string, action: string): $CancellablePromise<void> {
    return $Call.ByID(2057677570, card, action);
}

/**
 * Programs answers with what this client may see, which is the registry's own
 * answer and not a filtered copy of it (section 14 decided visibility at
 * connect time).
 */
export function Programs(): $CancellablePromise<$models.Program[]> {
    return $Call.ByID(1823204778).then(($result: any) => {
        return $$createType10($result);
    });
}

/**
 * Supervise starts, stops or restarts one program, the card's three buttons
 * (plan/55, requirement 42). The verbs are rig's own; the window adds
 * nothing but the call. Any other action is refused here rather than passed
 * through, so the page cannot name a verb this method was not written for.
 */
export function Supervise(action: string, program: string): $CancellablePromise<$models.Running> {
    return $Call.ByID(3916844919, action, program).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * Supervision never returns an error, for Health's reason: an estate Rig
 * cannot be asked about is drawn from what Programs already said.
 */
export function Supervision(): $CancellablePromise<$models.Running[]> {
    return $Call.ByID(914839342).then(($result: any) => {
        return $$createType12($result);
    });
}

/**
 * TakeNeeds reports whether the tray asked for Needs you since the page
 * last looked, and forgets the ask.
 */
export function TakeNeeds(): $CancellablePromise<boolean> {
    return $Call.ByID(3997971277);
}

/**
 * Try calls one capability. args is the JSON object the panel's form built.
 * A refusal from rig is an answer, not an error: it comes back with OK false
 * and rig's own words, so the panel shows it where the result goes.
 */
export function Try(owner: string, id: string, args: string): $CancellablePromise<$models.TryResult> {
    return $Call.ByID(99210380, owner, id, args).then(($result: any) => {
        return $$createType13($result);
    });
}

// Private type creation functions
const $$createType0 = $models.Reply.createFrom;
const $$createType1 = $models.CardList.createFrom;
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $models.Capability.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.Deployment.createFrom;
const $$createType6 = $models.Guidelines.createFrom;
const $$createType7 = $models.Health.createFrom;
const $$createType8 = $models.NoteList.createFrom;
const $$createType9 = $models.Program.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = $models.Running.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.TryResult.createFrom;
