// The rig wire contract, major version 1.
//
// Versioned by major in the path (PLAN.md section 21): rig serves every wire
// major it has ever shipped, so v2 lands beside this file rather than
// replacing it.
//
// Framing is NOT in this file. A frame on the socket is a 4-byte big-endian
// length prefix followed by one encoded Frame. See internal/wire.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/rig/v1/wire.proto

package rigv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FrameKind says what a Frame is for.
//
// Zero is UNSPECIFIED and is refused at the daemon boundary rather than
// treated as a default (PLAN.md section 21: "meaningful enum zero is banned").
// A value this binary does not know is refused the same way, so a newer peer
// cannot have an unknown kind silently decode as something harmless.
type FrameKind int32

const (
	FrameKind_FRAME_KIND_UNSPECIFIED FrameKind = 0
	FrameKind_FRAME_KIND_REQUEST     FrameKind = 1 // opens a stream, carries the call
	FrameKind_FRAME_KIND_RESPONSE    FrameKind = 2 // terminal, carries the result
	FrameKind_FRAME_KIND_STREAM_DATA FrameKind = 3 // one frame of a stream that is still open
	FrameKind_FRAME_KIND_STREAM_END  FrameKind = 4 // terminal, closes a stream with no payload
	FrameKind_FRAME_KIND_ERROR       FrameKind = 5 // terminal, carries Status
	FrameKind_FRAME_KIND_CANCEL      FrameKind = 6 // caller-side cancellation of an open stream
)

// Enum value maps for FrameKind.
var (
	FrameKind_name = map[int32]string{
		0: "FRAME_KIND_UNSPECIFIED",
		1: "FRAME_KIND_REQUEST",
		2: "FRAME_KIND_RESPONSE",
		3: "FRAME_KIND_STREAM_DATA",
		4: "FRAME_KIND_STREAM_END",
		5: "FRAME_KIND_ERROR",
		6: "FRAME_KIND_CANCEL",
	}
	FrameKind_value = map[string]int32{
		"FRAME_KIND_UNSPECIFIED": 0,
		"FRAME_KIND_REQUEST":     1,
		"FRAME_KIND_RESPONSE":    2,
		"FRAME_KIND_STREAM_DATA": 3,
		"FRAME_KIND_STREAM_END":  4,
		"FRAME_KIND_ERROR":       5,
		"FRAME_KIND_CANCEL":      6,
	}
)

func (x FrameKind) Enum() *FrameKind {
	p := new(FrameKind)
	*p = x
	return p
}

func (x FrameKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FrameKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_wire_proto_enumTypes[0].Descriptor()
}

func (FrameKind) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_wire_proto_enumTypes[0]
}

func (x FrameKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FrameKind.Descriptor instead.
func (FrameKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_wire_proto_rawDescGZIP(), []int{0}
}

// Code is a wire-level status. Program-level failure is a RESPONSE payload,
// not an ERROR frame: an ERROR means the call did not reach the program or
// could not be understood.
type Code int32

const (
	Code_CODE_UNSPECIFIED Code = 0
	Code_CODE_OK          Code = 1
	Code_CODE_UNAVAILABLE Code = 2 // rig is not there, or is shutting down
	Code_CODE_NOT_FOUND   Code = 3 // no such program, method or stream
	Code_CODE_INVALID     Code = 4 // malformed frame, bad argument, unknown enum
	Code_CODE_DENIED      Code = 5 // refused by capabilities or house rules
	Code_CODE_DEADLINE    Code = 6 // the call's deadline passed
	Code_CODE_INTERNAL    Code = 7
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_OK",
		2: "CODE_UNAVAILABLE",
		3: "CODE_NOT_FOUND",
		4: "CODE_INVALID",
		5: "CODE_DENIED",
		6: "CODE_DEADLINE",
		7: "CODE_INTERNAL",
	}
	Code_value = map[string]int32{
		"CODE_UNSPECIFIED": 0,
		"CODE_OK":          1,
		"CODE_UNAVAILABLE": 2,
		"CODE_NOT_FOUND":   3,
		"CODE_INVALID":     4,
		"CODE_DENIED":      5,
		"CODE_DEADLINE":    6,
		"CODE_INTERNAL":    7,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_wire_proto_enumTypes[1].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_wire_proto_enumTypes[1]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_wire_proto_rawDescGZIP(), []int{1}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=rig.v1.Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_proto_rig_v1_wire_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_wire_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_wire_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNSPECIFIED
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Frame is the only thing that crosses the socket.
type Frame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifies one logical call. Odd ids are client-opened, even are
	// daemon-opened, so the two sides never collide without negotiation.
	StreamId uint32    `protobuf:"varint,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Kind     FrameKind `protobuf:"varint,2,opt,name=kind,proto3,enum=rig.v1.FrameKind" json:"kind,omitempty"`
	// Dotted method name: "rig.ping", "shelf.reindex". Set on REQUEST only.
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	// Client-generated, stable across a retry. rig dedups against a bounded
	// window and returns the original response (PLAN.md section 4), so a
	// retried mutating call applies once. Set on REQUEST only.
	RequestId string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// The encoded body. Its type is implied by method and kind.
	Payload []byte `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// Set on ERROR only.
	Status        *Status `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Frame) Reset() {
	*x = Frame{}
	mi := &file_proto_rig_v1_wire_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Frame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Frame) ProtoMessage() {}

func (x *Frame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_wire_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Frame.ProtoReflect.Descriptor instead.
func (*Frame) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_wire_proto_rawDescGZIP(), []int{1}
}

func (x *Frame) GetStreamId() uint32 {
	if x != nil {
		return x.StreamId
	}
	return 0
}

func (x *Frame) GetKind() FrameKind {
	if x != nil {
		return x.Kind
	}
	return FrameKind_FRAME_KIND_UNSPECIFIED
}

func (x *Frame) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Frame) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Frame) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Frame) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoed back verbatim, so a caller can prove the round trip is its own.
	Nonce         []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_rig_v1_wire_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_wire_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_wire_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Program       string                 `protobuf:"bytes,2,opt,name=program,proto3" json:"program,omitempty"` // who answered
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"` // that program's own version string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_rig_v1_wire_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_wire_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_wire_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *PingResponse) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

func (x *PingResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_rig_v1_wire_proto protoreflect.FileDescriptor

const file_proto_rig_v1_wire_proto_rawDesc = "" +
	"\n" +
	"\x17proto/rig/v1/wire.proto\x12\x06rig.v1\"D\n" +
	"\x06Status\x12 \n" +
	"\x04code\x18\x01 \x01(\x0e2\f.rig.v1.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc4\x01\n" +
	"\x05Frame\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\rR\bstreamId\x12%\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.rig.v1.FrameKindR\x04kind\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12&\n" +
	"\x06status\x18\x06 \x01(\v2\x0e.rig.v1.StatusR\x06status\"#\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\"X\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x18\n" +
	"\aprogram\x18\x02 \x01(\tR\aprogram\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion*\xbc\x01\n" +
	"\tFrameKind\x12\x1a\n" +
	"\x16FRAME_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FRAME_KIND_REQUEST\x10\x01\x12\x17\n" +
	"\x13FRAME_KIND_RESPONSE\x10\x02\x12\x1a\n" +
	"\x16FRAME_KIND_STREAM_DATA\x10\x03\x12\x19\n" +
	"\x15FRAME_KIND_STREAM_END\x10\x04\x12\x14\n" +
	"\x10FRAME_KIND_ERROR\x10\x05\x12\x15\n" +
	"\x11FRAME_KIND_CANCEL\x10\x06*\x9c\x01\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCODE_OK\x10\x01\x12\x14\n" +
	"\x10CODE_UNAVAILABLE\x10\x02\x12\x12\n" +
	"\x0eCODE_NOT_FOUND\x10\x03\x12\x10\n" +
	"\fCODE_INVALID\x10\x04\x12\x0f\n" +
	"\vCODE_DENIED\x10\x05\x12\x11\n" +
	"\rCODE_DEADLINE\x10\x06\x12\x11\n" +
	"\rCODE_INTERNAL\x10\aB0Z.github.com/boris-milner/rig/proto/rig/v1;rigv1b\x06proto3"

var (
	file_proto_rig_v1_wire_proto_rawDescOnce sync.Once
	file_proto_rig_v1_wire_proto_rawDescData []byte
)

func file_proto_rig_v1_wire_proto_rawDescGZIP() []byte {
	file_proto_rig_v1_wire_proto_rawDescOnce.Do(func() {
		file_proto_rig_v1_wire_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rig_v1_wire_proto_rawDesc), len(file_proto_rig_v1_wire_proto_rawDesc)))
	})
	return file_proto_rig_v1_wire_proto_rawDescData
}

var file_proto_rig_v1_wire_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_rig_v1_wire_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_rig_v1_wire_proto_goTypes = []any{
	(FrameKind)(0),       // 0: rig.v1.FrameKind
	(Code)(0),            // 1: rig.v1.Code
	(*Status)(nil),       // 2: rig.v1.Status
	(*Frame)(nil),        // 3: rig.v1.Frame
	(*PingRequest)(nil),  // 4: rig.v1.PingRequest
	(*PingResponse)(nil), // 5: rig.v1.PingResponse
}
var file_proto_rig_v1_wire_proto_depIdxs = []int32{
	1, // 0: rig.v1.Status.code:type_name -> rig.v1.Code
	0, // 1: rig.v1.Frame.kind:type_name -> rig.v1.FrameKind
	2, // 2: rig.v1.Frame.status:type_name -> rig.v1.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_rig_v1_wire_proto_init() }
func file_proto_rig_v1_wire_proto_init() {
	if File_proto_rig_v1_wire_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rig_v1_wire_proto_rawDesc), len(file_proto_rig_v1_wire_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rig_v1_wire_proto_goTypes,
		DependencyIndexes: file_proto_rig_v1_wire_proto_depIdxs,
		EnumInfos:         file_proto_rig_v1_wire_proto_enumTypes,
		MessageInfos:      file_proto_rig_v1_wire_proto_msgTypes,
	}.Build()
	File_proto_rig_v1_wire_proto = out.File
	file_proto_rig_v1_wire_proto_goTypes = nil
	file_proto_rig_v1_wire_proto_depIdxs = nil
}
