// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as RigService from "./rigservice.js";
export {
    RigService
};

export type {
    Health,
    Program
} from "./models.js";
