// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Health is what the status strip renders.
 * 
 * Detached is section 5g's fourth state: the window is up and the daemon is
 * not. The strip has to be able to say that, because a rail with no programs
 * in it looks identical to a rail whose daemon died.
 */
export interface Health {
    "connected": boolean;
    "socket": string;
    "detail": string;
    "programs": number;
}

/**
 * Program is one registered program, flattened for the rail.
 * 
 * Deliberately NOT here: an identity hue. Section 11 gives a program one
 * ownable hue and says a program without one leaves the shell achromatic, but
 * rigv1.Identity carries id, name, version, icon and description and no hue at
 * all - so every program is achromatic today, and not by choice. Deriving one
 * from the id would fake a declaration the program never made. It is the first
 * field the shell found missing from section 5e; the wire is not this session's
 * to change.
 */
export interface Program {
    "id": string;
    "name": string;
    "version": string;
    "icon": string;
    "description": string;
    "coverage": string;
    "coverageNote": string;
    "services": string[] | null;
    "hosted": boolean;
    "commands": number;
}
