// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Blocked is an item that cannot proceed, with what is holding it.
 */
export class Blocked {
    "item": string;
    "title": string;
    "blockers": Blocker[];

    /** Creates a new Blocked instance. */
    constructor($$source: Partial<Blocked> = {}) {
        if (!("item" in $$source)) {
            this["item"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("blockers" in $$source)) {
            this["blockers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Blocked instance from a string or object.
     */
    static createFrom($$source: any = {}): Blocked {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("blockers" in $$parsedSource) {
            $$parsedSource["blockers"] = $$createField2_0($$parsedSource["blockers"]);
        }
        return new Blocked($$parsedSource as Partial<Blocked>);
    }
}

/**
 * Blocker is one thing holding an item up, WITH ITS OWN STATE.
 * 
 * The state is carried rather than dropped because "blocked by B12" and
 * "blocked by B12, which is itself blocked" are different situations for a
 * reader deciding what to pick up, and the wire already knows which.
 */
export class Blocker {
    "id": string;
    "title": string;
    "state": string;

    /** Creates a new Blocker instance. */
    constructor($$source: Partial<Blocker> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Blocker instance from a string or object.
     */
    static createFrom($$source: any = {}): Blocker {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Blocker($$parsedSource as Partial<Blocker>);
    }
}

/**
 * Brief is one project or case, flattened for the tab.
 */
export class Brief {
    "project": string;

    /**
     * `project` or `case`, and it decides what the rest means: a case has no
     * semver and its status reads open/resolved rather than idea/active.
     */
    "kind": string;
    "title": string;
    "status": string;
    "semver": string;
    "open": Item[];
    "nextUp": Item[];
    "blocked": Blocked[];
    "cycles": string[][];
    "notes": Note[];
    "caseNotes": Note[];
    "coarseCitations": number;
    "health": ProjectionHealth;
    "sections": SectionStatus[];

    /** Creates a new Brief instance. */
    constructor($$source: Partial<Brief> = {}) {
        if (!("project" in $$source)) {
            this["project"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("semver" in $$source)) {
            this["semver"] = "";
        }
        if (!("open" in $$source)) {
            this["open"] = [];
        }
        if (!("nextUp" in $$source)) {
            this["nextUp"] = [];
        }
        if (!("blocked" in $$source)) {
            this["blocked"] = [];
        }
        if (!("cycles" in $$source)) {
            this["cycles"] = [];
        }
        if (!("notes" in $$source)) {
            this["notes"] = [];
        }
        if (!("caseNotes" in $$source)) {
            this["caseNotes"] = [];
        }
        if (!("coarseCitations" in $$source)) {
            this["coarseCitations"] = 0;
        }
        if (!("health" in $$source)) {
            this["health"] = (new ProjectionHealth());
        }
        if (!("sections" in $$source)) {
            this["sections"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Brief instance from a string or object.
     */
    static createFrom($$source: any = {}): Brief {
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType3;
        const $$createField7_0 = $$createType5;
        const $$createField8_0 = $$createType7;
        const $$createField9_0 = $$createType9;
        const $$createField10_0 = $$createType9;
        const $$createField12_0 = $$createType10;
        const $$createField13_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("open" in $$parsedSource) {
            $$parsedSource["open"] = $$createField5_0($$parsedSource["open"]);
        }
        if ("nextUp" in $$parsedSource) {
            $$parsedSource["nextUp"] = $$createField6_0($$parsedSource["nextUp"]);
        }
        if ("blocked" in $$parsedSource) {
            $$parsedSource["blocked"] = $$createField7_0($$parsedSource["blocked"]);
        }
        if ("cycles" in $$parsedSource) {
            $$parsedSource["cycles"] = $$createField8_0($$parsedSource["cycles"]);
        }
        if ("notes" in $$parsedSource) {
            $$parsedSource["notes"] = $$createField9_0($$parsedSource["notes"]);
        }
        if ("caseNotes" in $$parsedSource) {
            $$parsedSource["caseNotes"] = $$createField10_0($$parsedSource["caseNotes"]);
        }
        if ("health" in $$parsedSource) {
            $$parsedSource["health"] = $$createField12_0($$parsedSource["health"]);
        }
        if ("sections" in $$parsedSource) {
            $$parsedSource["sections"] = $$createField13_0($$parsedSource["sections"]);
        }
        return new Brief($$parsedSource as Partial<Brief>);
    }
}

/**
 * Deployment is what is actually RUNNING, artefact by artefact, and whether the
 * artefacts agree with each other.
 * 
 * ⛔ IT EXISTS BECAUSE `make install` REPORTED SUCCESS OVER A WINDOW IT DOES NOT
 * TOUCH, AND NOBODY COULD SEE IT FOR THIRTEEN HOURS (B89). The Makefile's
 * install/install-window split is deliberate and right; the consequence nobody
 * accounted for is that a person who deploys and then looks at the window has
 * deployed the daemon and is looking at something else. Telling a stale window
 * from a current one took four separate commands and a screenshot's footer.
 * 
 * ⛔ SO THE PANEL OWES THIS BEFORE IT OWES A BUTTON. Boris asked for a
 * management panel and said "redeployment should be trivial and automatic"
 * (plan/11, B90). Two buttons would have produced B89 again, because somebody
 * still has to know to press the second one. A redeploy control that cannot say
 * what is currently running is a button that reports success over the same
 * failure.
 * 
 * WHAT IT DOES NOT DO: it does not compare against the SOURCE TREE. An installed
 * window has no tree to read, and a "built" column derived from one would be
 * absent on exactly the machine that needs it. This compares the artefacts that
 * are running to each other, which is the comparison B89 actually needed.
 */
export class Deployment {
    /**
     * WindowVersion and its siblings are this binary's own ldflags stamp.
     */
    "windowVersion": string;
    "windowCommit": string;
    "windowBuilt": string;

    /**
     * DaemonVersion comes over the socket from the daemon that is answering
     * right now, never from a file on disk.
     */
    "daemonVersion": string;
    "daemonWire": string;
    "windowWire": string;
    "epoch": number;

    /**
     * Reached is false when the daemon did not answer. ⛔ IT IS NOT A SKEW:
     * "these disagree" and "I could not ask" are different facts and a panel
     * that renders them the same way is the B89 defect in a new place.
     */
    "reached": boolean;

    /**
     * Agree is only meaningful when Reached. Verdict says why in a person's
     * words, and it is the line the panel leads with.
     */
    "agree": boolean;
    "verdict": string;

    /** Creates a new Deployment instance. */
    constructor($$source: Partial<Deployment> = {}) {
        if (!("windowVersion" in $$source)) {
            this["windowVersion"] = "";
        }
        if (!("windowCommit" in $$source)) {
            this["windowCommit"] = "";
        }
        if (!("windowBuilt" in $$source)) {
            this["windowBuilt"] = "";
        }
        if (!("daemonVersion" in $$source)) {
            this["daemonVersion"] = "";
        }
        if (!("daemonWire" in $$source)) {
            this["daemonWire"] = "";
        }
        if (!("windowWire" in $$source)) {
            this["windowWire"] = "";
        }
        if (!("epoch" in $$source)) {
            this["epoch"] = 0;
        }
        if (!("reached" in $$source)) {
            this["reached"] = false;
        }
        if (!("agree" in $$source)) {
            this["agree"] = false;
        }
        if (!("verdict" in $$source)) {
            this["verdict"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Deployment instance from a string or object.
     */
    static createFrom($$source: any = {}): Deployment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Deployment($$parsedSource as Partial<Deployment>);
    }
}

/**
 * Health is what the status strip renders.
 * 
 * Detached is section 5g's fourth state: the window is up and the daemon is
 * not. The strip has to be able to say that, because a rail with no programs
 * in it looks identical to a rail whose daemon died.
 */
export class Health {
    "connected": boolean;
    "socket": string;
    "detail": string;
    "programs": number;

    /** Creates a new Health instance. */
    constructor($$source: Partial<Health> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("socket" in $$source)) {
            this["socket"] = "";
        }
        if (!("detail" in $$source)) {
            this["detail"] = "";
        }
        if (!("programs" in $$source)) {
            this["programs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     */
    static createFrom($$source: any = {}): Health {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Health($$parsedSource as Partial<Health>);
    }
}

/**
 * Item is one work item as the brief sees it.
 */
export class Item {
    "id": string;
    "title": string;
    "state": string;

    /**
     * Unix nanoseconds, or 0 when the item has never been stepped. The view
     * formats it; a pre-formatted age here would be wrong the moment the
     * window sat open, which is exactly what a deferred-live-update surface
     * must not do.
     */
    "sinceUnixNano": number;
    "note": string;

    /**
     * ⛔ WHAT MAKES A ROW READABLE, AND IT REACHED THE WINDOW FOR THE FIRST
     * TIME ON 2026-09-17. The store computed all of these and the daemon's
     * itemToWire dropped them, so every row here was a truncated title with
     * nothing behind it - which is exactly what Boris called not user
     * friendly, and why clicking a row could only ever show the same line
     * again.
     */
    "descriptionShort": string;
    "priority": string;

    /**
     * The RECORD's status (`idea`, `active`), NOT the latest step's State.
     */
    "status": string;
    "owner": string;
    "tags": string[];
    "targetDate": string;
    "semver": string;

    /**
     * `task`, `bug`, `idea`, or empty for untyped. The row draws an icon for
     * it; an unknown value draws no icon and renders as its own word, because
     * the set is open.
     */
    "itemType": string;

    /** Creates a new Item instance. */
    constructor($$source: Partial<Item> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("sinceUnixNano" in $$source)) {
            this["sinceUnixNano"] = 0;
        }
        if (!("note" in $$source)) {
            this["note"] = "";
        }
        if (!("descriptionShort" in $$source)) {
            this["descriptionShort"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("owner" in $$source)) {
            this["owner"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = [];
        }
        if (!("targetDate" in $$source)) {
            this["targetDate"] = "";
        }
        if (!("semver" in $$source)) {
            this["semver"] = "";
        }
        if (!("itemType" in $$source)) {
            this["itemType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Item instance from a string or object.
     */
    static createFrom($$source: any = {}): Item {
        const $$createField9_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField9_0($$parsedSource["tags"]);
        }
        return new Item($$parsedSource as Partial<Item>);
    }
}

/**
 * Note is a project note, carrying its priority and what it is about.
 */
export class Note {
    "id": string;
    "body": string;
    "priority": string;
    "about": string;

    /** Creates a new Note instance. */
    constructor($$source: Partial<Note> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("priority" in $$source)) {
            this["priority"] = "";
        }
        if (!("about" in $$source)) {
            this["about"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Note instance from a string or object.
     */
    static createFrom($$source: any = {}): Note {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Note($$parsedSource as Partial<Note>);
    }
}

/**
 * Program is one registered program, flattened for the rail.
 * 
 * Deliberately NOT here: an identity hue. Section 11 gives a program one
 * ownable hue and says a program without one leaves the shell achromatic, but
 * rigv1.Identity carries id, name, version, icon and description and no hue at
 * all - so every program is achromatic today, and not by choice. Deriving one
 * from the id would fake a declaration the program never made. It is the first
 * field the shell found missing from section 5e; the wire is not this session's
 * to change.
 */
export class Program {
    "id": string;
    "name": string;
    "version": string;
    "icon": string;
    "description": string;
    "coverage": string;
    "coverageNote": string;
    "services": string[];
    "hosted": boolean;
    "commands": number;

    /**
     * Where the program serves its own HTML, empty if it serves none.
     * Section 11's three tiers turn on this one field: empty means rig draws
     * the pane from what was declared, and a value means the program draws it.
     * rig refuses anything but a loopback origin at registration, so by the
     * time a value reaches here it has already been checked.
     */
    "paneUrl": string;

    /** Creates a new Program instance. */
    constructor($$source: Partial<Program> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("coverage" in $$source)) {
            this["coverage"] = "";
        }
        if (!("coverageNote" in $$source)) {
            this["coverageNote"] = "";
        }
        if (!("services" in $$source)) {
            this["services"] = [];
        }
        if (!("hosted" in $$source)) {
            this["hosted"] = false;
        }
        if (!("commands" in $$source)) {
            this["commands"] = 0;
        }
        if (!("paneUrl" in $$source)) {
            this["paneUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Program instance from a string or object.
     */
    static createFrom($$source: any = {}): Program {
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("services" in $$parsedSource) {
            $$parsedSource["services"] = $$createField7_0($$parsedSource["services"]);
        }
        return new Program($$parsedSource as Partial<Program>);
    }
}

/**
 * ProjectRef is one project or case the store holds.
 */
export class ProjectRef {
    "id": string;
    "title": string;
    "kind": string;
    "status": string;

    /** Creates a new ProjectRef instance. */
    constructor($$source: Partial<ProjectRef> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectRef instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectRef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectRef($$parsedSource as Partial<ProjectRef>);
    }
}

/**
 * ProjectionHealth is section 39's three projection rows. Every one is NOT
 * COMPUTED today; read the matching SectionStatus before rendering any of
 * them.
 * 
 * Named for the projection rather than called Health, because service.go's
 * Health is the window's own reachability of the daemon. Two things called
 * Health on one service is how a view binds the wrong one.
 */
export class ProjectionHealth {
    "projectionBehindCommits": number;
    "pendingEntries": number;
    "localOnly": boolean;
    "localOnlyReason": string;

    /** Creates a new ProjectionHealth instance. */
    constructor($$source: Partial<ProjectionHealth> = {}) {
        if (!("projectionBehindCommits" in $$source)) {
            this["projectionBehindCommits"] = 0;
        }
        if (!("pendingEntries" in $$source)) {
            this["pendingEntries"] = 0;
        }
        if (!("localOnly" in $$source)) {
            this["localOnly"] = false;
        }
        if (!("localOnlyReason" in $$source)) {
            this["localOnlyReason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProjectionHealth instance from a string or object.
     */
    static createFrom($$source: any = {}): ProjectionHealth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProjectionHealth($$parsedSource as Partial<ProjectionHealth>);
    }
}

/**
 * RecordRow is one record as a list needs it: enough to render a row and open
 * it, and not the whole store's prose twice.
 */
export class RecordRow {
    "id": string;
    "version": number;
    "kind": string;
    "title": string;

    /**
     * Section is the grouping a reader actually thinks in - "39", "11" - and it
     * is FREE: a requirement's id leads with its section number, by the id
     * scheme Boris ruled on 2026-09-18. Empty when the id has no such prefix,
     * which is every decision.
     */
    "section": string;
    "sectionTitle": string;
    "body": string;

    /**
     * Source and Line are where the document says it, so a reader can go and
     * look. They are the fields the seeder writes, unaltered.
     */
    "source": string;
    "line": string;
    "tags": string;

    /**
     * Retracted is stated rather than filtered: a record the store is still
     * holding but no longer standing behind is a thing a reader must be able
     * to see, and silently dropping it is how a list lies.
     */
    "retracted": boolean;

    /** Creates a new RecordRow instance. */
    constructor($$source: Partial<RecordRow> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("section" in $$source)) {
            this["section"] = "";
        }
        if (!("sectionTitle" in $$source)) {
            this["sectionTitle"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = "";
        }
        if (!("tags" in $$source)) {
            this["tags"] = "";
        }
        if (!("retracted" in $$source)) {
            this["retracted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecordRow instance from a string or object.
     */
    static createFrom($$source: any = {}): RecordRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RecordRow($$parsedSource as Partial<RecordRow>);
    }
}

/**
 * SectionStatus is one of the brief's eleven sections and what it can say.
 * 
 * ⛔ THIS IS THE FIELD THAT MAKES EVERY OTHER ONE HONEST, and it is not
 * optional decoration for the view. Seven of the eleven sections are NOT
 * COMPUTED today - the standards register does not exist, the must-read gate is
 * unbuilt on both halves, and the projection is unwritten. Without this, an
 * empty `blocked` list and an unbuilt `drift` list render identically, and a
 * reader concludes this project has no drift when the truth is that rig cannot
 * yet know. The proto says it outright: "A caller that renders a section
 * without reading its status is the failure this field exists to prevent."
 */
export class SectionStatus {
    "section": string;
    "state": string;
    "reason": string;

    /** Creates a new SectionStatus instance. */
    constructor($$source: Partial<SectionStatus> = {}) {
        if (!("section" in $$source)) {
            this["section"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SectionStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): SectionStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SectionStatus($$parsedSource as Partial<SectionStatus>);
    }
}

// Private type creation functions
const $$createType0 = Blocker.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Item.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = Blocked.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $Create.Array($Create.Any);
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Note.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = ProjectionHealth.createFrom;
const $$createType11 = SectionStatus.createFrom;
const $$createType12 = $Create.Array($$createType11);
