// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * RigService is the window's only route to the daemon.
 * 
 * It dials per call rather than holding a connection, which is what makes
 * section 11's "the window survives a daemon restart" true for free: there is
 * no socket to go stale, and the next repaint reconnects. Section 22's split
 * pays for it - a unix socket dial is microseconds, and the alternative is
 * reconnect logic that M6 is going to write properly anyway.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Build is the four versions the binary carries, so the strip can show which
 * window is running without a person going to a terminal.
 */
export function Build(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1191479857).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Deployment never returns an error, for Health's reason: not reaching rig is a
 * state to draw, not a failure to handle.
 */
export function Deployment(): $CancellablePromise<$models.Deployment> {
    return $Call.ByID(69816036).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Health never returns an error: not reaching rig is a state the strip draws,
 * not a failure the window has to handle.
 */
export function Health(): $CancellablePromise<$models.Health> {
    return $Call.ByID(2625630141).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Programs answers with what this client may see, which is the registry's own
 * answer and not a filtered copy of it (section 14 decided visibility at
 * connect time).
 */
export function Programs(): $CancellablePromise<$models.Program[]> {
    return $Call.ByID(1823204778).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.Deployment.createFrom;
const $$createType2 = $models.Health.createFrom;
const $$createType3 = $models.Program.createFrom;
const $$createType4 = $Create.Array($$createType3);
