// The rig wire contract, major version 1: the registry and the estate.
//
// Part of proto package rig.v1 exactly as wire.proto is, so every message
// keeps its full name, its numbers and its bytes on the wire. It is a
// separate FILE only so its generated Go code is a separate package: a
// program links the handshake in wire.proto and none of this, and the
// window links this and none of verbs.proto. See wire.proto's header.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/rig/v1/registry.proto

package registryv1

import (
	v1 "github.com/borismilner/rig/proto/rig/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Depth is how much of the estate a read wants (section 9).
//
// Section 9's argument for four meta tools is a context budget: fifteen
// programs with twenty commands each is three hundred tools, and handing an
// agent all of it "destroys its context before it has done anything". So
// `list` "returns the estate at whatever depth is asked for".
//
// The line between the last two is one sentence: DEPTH_COMMANDS carries what
// an agent picks a command BY, DEPTH_FULL carries what it calls the command
// WITH. Scalars and the one-line summary are how you choose; schemas,
// examples, preconditions and prose are how you invoke.
type Depth int32

const (
	Depth_DEPTH_UNSPECIFIED Depth = 0
	// The estate itself: who is registered and how much of rig each has
	// adopted. No commands, no preamble.
	Depth_DEPTH_PROGRAMS Depth = 1
	// Every command's scalar properties and its summary - enough to choose
	// one, and nothing that costs a schema.
	Depth_DEPTH_COMMANDS Depth = 2
	// Everything this principal may see, preamble and argument schemas
	// included.
	Depth_DEPTH_FULL Depth = 3
)

// Enum value maps for Depth.
var (
	Depth_name = map[int32]string{
		0: "DEPTH_UNSPECIFIED",
		1: "DEPTH_PROGRAMS",
		2: "DEPTH_COMMANDS",
		3: "DEPTH_FULL",
	}
	Depth_value = map[string]int32{
		"DEPTH_UNSPECIFIED": 0,
		"DEPTH_PROGRAMS":    1,
		"DEPTH_COMMANDS":    2,
		"DEPTH_FULL":        3,
	}
)

func (x Depth) Enum() *Depth {
	p := new(Depth)
	*p = x
	return p
}

func (x Depth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Depth) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[0].Descriptor()
}

func (Depth) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[0]
}

func (x Depth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Depth.Descriptor instead.
func (Depth) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{0}
}

// EstateRole is what an estate is FOR.
//
// UNNAMED HAS A NUMBER OF ITS OWN AND THE ZERO IS NOT IT. proto3 cannot tell
// an unset scalar from a zero one, so a daemon that carries this field and
// fails to set it - a bug, or a build where the field landed and the setter
// did not - would render as "this is an unnamed estate" and an agent would
// branch on it. An unnamed estate reads as ephemeral and disposable and
// production does not, so the safe guess and the useful guess point opposite
// ways. Zero therefore keeps section 21's meaning, "nothing was said", and the
// identity fact gets a value of its own.
type EstateRole int32

const (
	EstateRole_ESTATE_ROLE_UNSPECIFIED EstateRole = 0 // nothing was said. Never a fact about an estate
	EstateRole_ESTATE_ROLE_UNNAMED     EstateRole = 1 // deliberately unnamed: a test, a build, an ephemeral run
	EstateRole_ESTATE_ROLE_PRODUCTION  EstateRole = 2
	EstateRole_ESTATE_ROLE_DEVELOPMENT EstateRole = 3
)

// Enum value maps for EstateRole.
var (
	EstateRole_name = map[int32]string{
		0: "ESTATE_ROLE_UNSPECIFIED",
		1: "ESTATE_ROLE_UNNAMED",
		2: "ESTATE_ROLE_PRODUCTION",
		3: "ESTATE_ROLE_DEVELOPMENT",
	}
	EstateRole_value = map[string]int32{
		"ESTATE_ROLE_UNSPECIFIED": 0,
		"ESTATE_ROLE_UNNAMED":     1,
		"ESTATE_ROLE_PRODUCTION":  2,
		"ESTATE_ROLE_DEVELOPMENT": 3,
	}
)

func (x EstateRole) Enum() *EstateRole {
	p := new(EstateRole)
	*p = x
	return p
}

func (x EstateRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EstateRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[1].Descriptor()
}

func (EstateRole) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[1]
}

func (x EstateRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EstateRole.Descriptor instead.
func (EstateRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{1}
}

// AgentBox's five, in rising order of how loudly they are drawn.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_INFO        Severity = 1
	Severity_SEVERITY_SUCCESS     Severity = 2
	Severity_SEVERITY_WARNING     Severity = 3
	Severity_SEVERITY_ERROR       Severity = 4
	Severity_SEVERITY_URGENT      Severity = 5
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "SEVERITY_UNSPECIFIED",
		1: "SEVERITY_INFO",
		2: "SEVERITY_SUCCESS",
		3: "SEVERITY_WARNING",
		4: "SEVERITY_ERROR",
		5: "SEVERITY_URGENT",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_INFO":        1,
		"SEVERITY_SUCCESS":     2,
		"SEVERITY_WARNING":     3,
		"SEVERITY_ERROR":       4,
		"SEVERITY_URGENT":      5,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[2].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[2]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{2}
}

// Do Not Disturb (section 12): while it is on, a notification is filed in the
// record and not drawn. An urgent one is always drawn.
type DndChange int32

const (
	DndChange_DND_CHANGE_UNSPECIFIED DndChange = 0
	// Answer the state and change nothing.
	DndChange_DND_CHANGE_QUERY DndChange = 1
	DndChange_DND_CHANGE_ON    DndChange = 2
	DndChange_DND_CHANGE_OFF   DndChange = 3
)

// Enum value maps for DndChange.
var (
	DndChange_name = map[int32]string{
		0: "DND_CHANGE_UNSPECIFIED",
		1: "DND_CHANGE_QUERY",
		2: "DND_CHANGE_ON",
		3: "DND_CHANGE_OFF",
	}
	DndChange_value = map[string]int32{
		"DND_CHANGE_UNSPECIFIED": 0,
		"DND_CHANGE_QUERY":       1,
		"DND_CHANGE_ON":          2,
		"DND_CHANGE_OFF":         3,
	}
)

func (x DndChange) Enum() *DndChange {
	p := new(DndChange)
	*p = x
	return p
}

func (x DndChange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DndChange) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[3].Descriptor()
}

func (DndChange) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[3]
}

func (x DndChange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DndChange.Descriptor instead.
func (DndChange) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{3}
}

// Sounds and speech (section 12, S1-S5): the toast sound, reading toasts
// aloud, and one mute over both. The settings survive a restart. A field left
// unspecified changes nothing, so an empty request only asks.
type SoundMute int32

const (
	SoundMute_SOUND_MUTE_UNSPECIFIED SoundMute = 0
	SoundMute_SOUND_MUTE_ON          SoundMute = 1
	SoundMute_SOUND_MUTE_OFF         SoundMute = 2
)

// Enum value maps for SoundMute.
var (
	SoundMute_name = map[int32]string{
		0: "SOUND_MUTE_UNSPECIFIED",
		1: "SOUND_MUTE_ON",
		2: "SOUND_MUTE_OFF",
	}
	SoundMute_value = map[string]int32{
		"SOUND_MUTE_UNSPECIFIED": 0,
		"SOUND_MUTE_ON":          1,
		"SOUND_MUTE_OFF":         2,
	}
)

func (x SoundMute) Enum() *SoundMute {
	p := new(SoundMute)
	*p = x
	return p
}

func (x SoundMute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SoundMute) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[4].Descriptor()
}

func (SoundMute) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[4]
}

func (x SoundMute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SoundMute.Descriptor instead.
func (SoundMute) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{4}
}

// How much of a drawn toast is read aloud.
type ReadAloud int32

const (
	ReadAloud_READ_ALOUD_UNSPECIFIED    ReadAloud = 0
	ReadAloud_READ_ALOUD_OFF            ReadAloud = 1
	ReadAloud_READ_ALOUD_TITLE          ReadAloud = 2
	ReadAloud_READ_ALOUD_TITLE_AND_BODY ReadAloud = 3
)

// Enum value maps for ReadAloud.
var (
	ReadAloud_name = map[int32]string{
		0: "READ_ALOUD_UNSPECIFIED",
		1: "READ_ALOUD_OFF",
		2: "READ_ALOUD_TITLE",
		3: "READ_ALOUD_TITLE_AND_BODY",
	}
	ReadAloud_value = map[string]int32{
		"READ_ALOUD_UNSPECIFIED":    0,
		"READ_ALOUD_OFF":            1,
		"READ_ALOUD_TITLE":          2,
		"READ_ALOUD_TITLE_AND_BODY": 3,
	}
)

func (x ReadAloud) Enum() *ReadAloud {
	p := new(ReadAloud)
	*p = x
	return p
}

func (x ReadAloud) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadAloud) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[5].Descriptor()
}

func (ReadAloud) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[5]
}

func (x ReadAloud) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadAloud.Descriptor instead.
func (ReadAloud) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{5}
}

// Which sound a drawn toast plays.
type ToastSound int32

const (
	ToastSound_TOAST_SOUND_UNSPECIFIED ToastSound = 0
	ToastSound_TOAST_SOUND_HAIL        ToastSound = 1
	ToastSound_TOAST_SOUND_BADGE       ToastSound = 2
	// The file rigd was started with (--toast-sound-file); refused without one.
	ToastSound_TOAST_SOUND_FILE ToastSound = 3
)

// Enum value maps for ToastSound.
var (
	ToastSound_name = map[int32]string{
		0: "TOAST_SOUND_UNSPECIFIED",
		1: "TOAST_SOUND_HAIL",
		2: "TOAST_SOUND_BADGE",
		3: "TOAST_SOUND_FILE",
	}
	ToastSound_value = map[string]int32{
		"TOAST_SOUND_UNSPECIFIED": 0,
		"TOAST_SOUND_HAIL":        1,
		"TOAST_SOUND_BADGE":       2,
		"TOAST_SOUND_FILE":        3,
	}
)

func (x ToastSound) Enum() *ToastSound {
	p := new(ToastSound)
	*p = x
	return p
}

func (x ToastSound) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToastSound) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[6].Descriptor()
}

func (ToastSound) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[6]
}

func (x ToastSound) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToastSound.Descriptor instead.
func (ToastSound) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{6}
}

// Program is one program as one principal may see it (section 14).
//
// It is Declaration minus scope: what a reader is shown, not what was stored.
// Section 5k's rule that no surface may imply completeness is why coverage
// travels with it.
//
// THIS COMMENT USED TO SAY "minus preamble and scope", AND THAT WAS THE BUG.
// Section 9 requires the preamble to be "returned by describe on the program",
// and a program has been able to declare one since M1 - accepted at hello,
// validated, stored in the registry - with no message on any path able to
// carry it back. It was a dead field for as long as it existed. Scope stays
// out: it is how rig decides who may see this program, not something the
// program said about itself.
type Program struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Identity     *v1.Identity           `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Coverage     v1.Coverage            `protobuf:"varint,2,opt,name=coverage,proto3,enum=rig.v1.Coverage" json:"coverage,omitempty"`
	CoverageNote string                 `protobuf:"bytes,3,opt,name=coverage_note,json=coverageNote,proto3" json:"coverage_note,omitempty"`
	SemanticsGen int32                  `protobuf:"varint,4,opt,name=semantics_gen,json=semanticsGen,proto3" json:"semantics_gen,omitempty"`
	Services     []string               `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
	Hosted       bool                   `protobuf:"varint,6,opt,name=hosted,proto3" json:"hosted,omitempty"`
	Commands     []*v1.Command          `protobuf:"bytes,7,rep,name=commands,proto3" json:"commands,omitempty"`
	// Where this program serves its own pane, validated at registration. A
	// reader gets it because the window is a reader like any other.
	PaneUrl string `protobuf:"bytes,8,opt,name=pane_url,json=paneUrl,proto3" json:"pane_url,omitempty"`
	// The kit elements this program declares (section 5h R3). A reader gets it
	// for the same reason it gets services: it is part of what the program said
	// about itself, not part of how anything draws it.
	Elements []string `protobuf:"bytes,9,rep,name=elements,proto3" json:"elements,omitempty"`
	// The one document an agent reads before touching this program (section 9).
	//
	// Carried at DEPTH_FULL only. It is prose, it can be long, and fifteen of
	// them in one list is the context cost section 9's whole tiering argument
	// exists to avoid - so it travels with describe and not with list.
	Preamble      string `protobuf:"bytes,10,opt,name=preamble,proto3" json:"preamble,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Program) Reset() {
	*x = Program{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetIdentity() *v1.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Program) GetCoverage() v1.Coverage {
	if x != nil {
		return x.Coverage
	}
	return v1.Coverage(0)
}

func (x *Program) GetCoverageNote() string {
	if x != nil {
		return x.CoverageNote
	}
	return ""
}

func (x *Program) GetSemanticsGen() int32 {
	if x != nil {
		return x.SemanticsGen
	}
	return 0
}

func (x *Program) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Program) GetHosted() bool {
	if x != nil {
		return x.Hosted
	}
	return false
}

func (x *Program) GetCommands() []*v1.Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Program) GetPaneUrl() string {
	if x != nil {
		return x.PaneUrl
	}
	return ""
}

func (x *Program) GetElements() []string {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *Program) GetPreamble() string {
	if x != nil {
		return x.Preamble
	}
	return ""
}

type ProgramsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How much to say about each program. Absent means DEPTH_FULL, and that is
	// a COMPATIBILITY rule rather than a default worth having: every caller
	// written before this field existed asked for everything, and proto3 gives
	// it the zero value whether it says so or not. The kernel refuses an
	// unspecified depth outright (section 21's enum rule); the boundary is
	// where the old wire's meaning is restored, so exactly one place has to
	// know that the two disagree.
	Depth         Depth `protobuf:"varint,1,opt,name=depth,proto3,enum=rig.v1.Depth" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramsRequest) Reset() {
	*x = ProgramsRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramsRequest) ProtoMessage() {}

func (x *ProgramsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramsRequest.ProtoReflect.Descriptor instead.
func (*ProgramsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ProgramsRequest) GetDepth() Depth {
	if x != nil {
		return x.Depth
	}
	return Depth_DEPTH_UNSPECIFIED
}

type ProgramsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only what the calling principal may see. An unscoped, unprivileged client
	// gets nothing; a program gets itself; a client of the owner's gets all of
	// it, because introspect was decided when the connection was made.
	Programs      []*Program `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramsResponse) Reset() {
	*x = ProgramsResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramsResponse) ProtoMessage() {}

func (x *ProgramsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramsResponse.ProtoReflect.Descriptor instead.
func (*ProgramsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ProgramsResponse) GetPrograms() []*Program {
	if x != nil {
		return x.Programs
	}
	return nil
}

type EstateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstateRequest) Reset() {
	*x = EstateRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstateRequest) ProtoMessage() {}

func (x *EstateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstateRequest.ProtoReflect.Descriptor instead.
func (*EstateRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{3}
}

type EstateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name this estate claimed, empty when it claimed none. Section 37's
	// precondition 6 makes it unique across the machine while it is held.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ROLE IS DERIVED FROM name BY THE DAEMON, AT REPLY TIME, AND IS NEVER
	// STORED AND NEVER ACCEPTED AS INPUT. A client must never send one and must
	// never infer the other.
	//
	// Both are carried on purpose even though the name set is closed at two
	// today and role is therefore derivable. With only the name, the derivation
	// `name == "production"` would live in every consumer - every agent, every
	// script, outside this repository and uncountable - and reopening the set
	// would break all of them silently. Here it lives in the daemon, once, and
	// reopening the set breaks nothing. The two cannot disagree because there is
	// no second place to write one.
	Role EstateRole `protobuf:"varint,2,opt,name=role,proto3,enum=rig.v1.EstateRole" json:"role,omitempty"`
	// The daemon's own build. The same value `rig.ping` returns when it is
	// addressed to rig itself, consolidated here so one call answers "who did I
	// reach" rather than requiring a caller to know to probe "rig".
	DaemonVersion string `protobuf:"bytes,3,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	// The wire contract's major. Carried for completeness rather than for skew
	// detection: the major rides the proto package path, so a client and a
	// daemon on different majors cannot connect at all and major skew is
	// structurally impossible rather than undetected.
	Wire string `protobuf:"bytes,4,opt,name=wire,proto3" json:"wire,omitempty"`
	// RIG'S OWN SEMANTIC GENERATION, FROM ITS SELF-DECLARATION, AND IT IS NOT A
	// PER-PROGRAM SKEW DETECTOR. Do not read this as "have the programs I use
	// changed meaning". That question is per-program, its answer is already on
	// the wire in Program.semantics_gen and already readable, and what it needs
	// is a consumer on the capability map. This field answers only "what
	// semantics does the daemon itself implement", which is what a client built
	// from the development tree needs when it reaches the production daemon.
	SemanticsGen int32 `protobuf:"varint,5,opt,name=semantics_gen,json=semanticsGen,proto3" json:"semantics_gen,omitempty"`
	// THE INCARNATION, AS OPPOSED TO THE IDENTITY. Every other field in this
	// message is identical across a restart - same name, same role, same build,
	// same wire, same generation - so an agent holding a handle from before
	// could not tell "same rig, still up" from "same rig, restarted under me",
	// and a lease it believes it holds may already be somebody else's. This is
	// the only field here that moves, and a caller that remembers the last one
	// it saw gets the distinction for free.
	//
	// Bumped unconditionally on every start, with nothing consulted (section
	// 37, precondition 4, and V15): the cost of treating a planned restart as a
	// crash is one re-acquisition, and the cost of the reverse is a fencing
	// token that outlives what it fences.
	//
	// ZERO MEANS NO PERSISTENT STATE, WHICH IS AN ANSWER RATHER THAN A HOLE. An
	// estate started without a name opens no store, because it has no name to
	// key a subtree to, so it has no epoch to report. A real epoch is always at
	// least 1, because the store bumps before it publishes, so 0 is
	// unambiguously "this estate has no persistent state" and cannot be
	// confused with a real one.
	Epoch uint64 `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// WHERE THIS ESTATE KEEPS ITS STORAGE (plan/48, R14-R15): the root the
	// daemon resolved at start from --root, RIG_ROOT or ~/.rig, or the scratch
	// root of an unnamed estate. The estate's own areas are under it.
	//
	// Walked against section 14's caller rows as the estate arm requires: it is
	// a path in the same user's home, a fact about this daemon, and no other
	// principal's data. Empty from a daemon that predates the field.
	Root          string `protobuf:"bytes,7,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstateResponse) Reset() {
	*x = EstateResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstateResponse) ProtoMessage() {}

func (x *EstateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstateResponse.ProtoReflect.Descriptor instead.
func (*EstateResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *EstateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EstateResponse) GetRole() EstateRole {
	if x != nil {
		return x.Role
	}
	return EstateRole_ESTATE_ROLE_UNSPECIFIED
}

func (x *EstateResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *EstateResponse) GetWire() string {
	if x != nil {
		return x.Wire
	}
	return ""
}

func (x *EstateResponse) GetSemanticsGen() int32 {
	if x != nil {
		return x.SemanticsGen
	}
	return 0
}

func (x *EstateResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *EstateResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

type Toast struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic for this daemon's life; the waiter's cursor.
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// The notification record's id.
	RecordId string   `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Severity Severity `protobuf:"varint,3,opt,name=severity,proto3,enum=rig.v1.Severity" json:"severity,omitempty"`
	Title    string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Body     string   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	// The sender: a registered program's id, else the caller's seat.
	Sender     string `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	AtUnixNano int64  `protobuf:"varint,7,opt,name=at_unix_nano,json=atUnixNano,proto3" json:"at_unix_nano,omitempty"`
	// Filed while Do Not Disturb was on, so it went to the record and not to
	// the screen. Never set on an urgent toast.
	Suppressed bool `protobuf:"varint,8,opt,name=suppressed,proto3" json:"suppressed,omitempty"`
	// The reply buttons the sender offered, in order. A toast with replies or
	// reply_text waits for its answer and never closes on its own (section 12,
	// Boris 2026-09-27).
	Replies []string `protobuf:"bytes,9,rep,name=replies,proto3" json:"replies,omitempty"`
	// The sender takes a free-text reply.
	ReplyText     bool `protobuf:"varint,10,opt,name=reply_text,json=replyText,proto3" json:"reply_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Toast) Reset() {
	*x = Toast{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Toast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Toast) ProtoMessage() {}

func (x *Toast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Toast.ProtoReflect.Descriptor instead.
func (*Toast) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{5}
}

func (x *Toast) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Toast) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *Toast) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *Toast) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Toast) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Toast) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Toast) GetAtUnixNano() int64 {
	if x != nil {
		return x.AtUnixNano
	}
	return 0
}

func (x *Toast) GetSuppressed() bool {
	if x != nil {
		return x.Suppressed
	}
	return false
}

func (x *Toast) GetReplies() []string {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *Toast) GetReplyText() bool {
	if x != nil {
		return x.ReplyText
	}
	return false
}

// NotifyRequest sends one. Severity is required; title up to 200 bytes, body
// up to 4 KiB.
type NotifyRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Severity Severity               `protobuf:"varint,1,opt,name=severity,proto3,enum=rig.v1.Severity" json:"severity,omitempty"`
	Title    string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body     string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Up to three reply buttons, each 1 to 40 bytes. The sender learns which
	// was pressed with toast.answer.
	Replies []string `protobuf:"bytes,4,rep,name=replies,proto3" json:"replies,omitempty"`
	// Offer a free-text reply as well as, or instead of, the buttons.
	ReplyText bool `protobuf:"varint,5,opt,name=reply_text,json=replyText,proto3" json:"reply_text,omitempty"`
	// A line written to be heard, up to 400 bytes. Read aloud in place of the
	// title or the body whenever toasts are read aloud at all (section 12, S6).
	Speak         string `protobuf:"bytes,6,opt,name=speak,proto3" json:"speak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyRequest) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *NotifyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotifyRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *NotifyRequest) GetReplies() []string {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *NotifyRequest) GetReplyText() bool {
	if x != nil {
		return x.ReplyText
	}
	return false
}

func (x *NotifyRequest) GetSpeak() string {
	if x != nil {
		return x.Speak
	}
	return ""
}

// ToastReplyRequest answers a toast that asked for a reply: a button's label,
// free text, or neither when the person closed it without answering. The
// first reply wins; a second is refused.
type ToastReplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Reply         string                 `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Dismissed     bool                   `protobuf:"varint,4,opt,name=dismissed,proto3" json:"dismissed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastReplyRequest) Reset() {
	*x = ToastReplyRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastReplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastReplyRequest) ProtoMessage() {}

func (x *ToastReplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastReplyRequest.ProtoReflect.Descriptor instead.
func (*ToastReplyRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{7}
}

func (x *ToastReplyRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ToastReplyRequest) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ToastReplyRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ToastReplyRequest) GetDismissed() bool {
	if x != nil {
		return x.Dismissed
	}
	return false
}

type ToastReplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        *ToastAnswer           `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastReplyResponse) Reset() {
	*x = ToastReplyResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastReplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastReplyResponse) ProtoMessage() {}

func (x *ToastReplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastReplyResponse.ProtoReflect.Descriptor instead.
func (*ToastReplyResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{8}
}

func (x *ToastReplyResponse) GetAnswer() *ToastAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

// ToastAnswer is what came back for one toast.
type ToastAnswer struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RecordId string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	// False while nobody has replied.
	Answered bool `protobuf:"varint,2,opt,name=answered,proto3" json:"answered,omitempty"`
	// The button pressed; empty for a free-text reply or a dismissal.
	Reply string `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	Text  string `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	// Closed without an answer.
	Dismissed bool `protobuf:"varint,5,opt,name=dismissed,proto3" json:"dismissed,omitempty"`
	// Who replied: the replying connection's seat.
	By            string `protobuf:"bytes,6,opt,name=by,proto3" json:"by,omitempty"`
	AtUnixNano    int64  `protobuf:"varint,7,opt,name=at_unix_nano,json=atUnixNano,proto3" json:"at_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastAnswer) Reset() {
	*x = ToastAnswer{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastAnswer) ProtoMessage() {}

func (x *ToastAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastAnswer.ProtoReflect.Descriptor instead.
func (*ToastAnswer) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{9}
}

func (x *ToastAnswer) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ToastAnswer) GetAnswered() bool {
	if x != nil {
		return x.Answered
	}
	return false
}

func (x *ToastAnswer) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

func (x *ToastAnswer) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ToastAnswer) GetDismissed() bool {
	if x != nil {
		return x.Dismissed
	}
	return false
}

func (x *ToastAnswer) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

func (x *ToastAnswer) GetAtUnixNano() int64 {
	if x != nil {
		return x.AtUnixNano
	}
	return 0
}

// ToastAnswerRequest waits for the reply to a toast the caller filed, up to
// timeout_ms (at most 60000); zero asks without waiting.
type ToastAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RecordId      string                 `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastAnswerRequest) Reset() {
	*x = ToastAnswerRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastAnswerRequest) ProtoMessage() {}

func (x *ToastAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastAnswerRequest.ProtoReflect.Descriptor instead.
func (*ToastAnswerRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{10}
}

func (x *ToastAnswerRequest) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ToastAnswerRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ToastAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        *ToastAnswer           `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastAnswerResponse) Reset() {
	*x = ToastAnswerResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastAnswerResponse) ProtoMessage() {}

func (x *ToastAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastAnswerResponse.ProtoReflect.Descriptor instead.
func (*ToastAnswerResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{11}
}

func (x *ToastAnswerResponse) GetAnswer() *ToastAnswer {
	if x != nil {
		return x.Answer
	}
	return nil
}

type NotifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Toast         *Toast                 `protobuf:"bytes,1,opt,name=toast,proto3" json:"toast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyResponse) GetToast() *Toast {
	if x != nil {
		return x.Toast
	}
	return nil
}

// ToastWaitRequest answers the toasts after `after` as soon as there are any,
// or an empty list once `timeout_ms` (at most 60000) has passed.
type ToastWaitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	After         uint64                 `protobuf:"varint,1,opt,name=after,proto3" json:"after,omitempty"`
	TimeoutMs     uint32                 `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastWaitRequest) Reset() {
	*x = ToastWaitRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastWaitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastWaitRequest) ProtoMessage() {}

func (x *ToastWaitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastWaitRequest.ProtoReflect.Descriptor instead.
func (*ToastWaitRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{13}
}

func (x *ToastWaitRequest) GetAfter() uint64 {
	if x != nil {
		return x.After
	}
	return 0
}

func (x *ToastWaitRequest) GetTimeoutMs() uint32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ToastWaitResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Toasts []*Toast               `protobuf:"bytes,1,rep,name=toasts,proto3" json:"toasts,omitempty"`
	// The newest seq the daemon has issued, so a waiter that starts late can
	// skip the backlog.
	Latest        uint64 `protobuf:"varint,2,opt,name=latest,proto3" json:"latest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastWaitResponse) Reset() {
	*x = ToastWaitResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastWaitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastWaitResponse) ProtoMessage() {}

func (x *ToastWaitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastWaitResponse.ProtoReflect.Descriptor instead.
func (*ToastWaitResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{14}
}

func (x *ToastWaitResponse) GetToasts() []*Toast {
	if x != nil {
		return x.Toasts
	}
	return nil
}

func (x *ToastWaitResponse) GetLatest() uint64 {
	if x != nil {
		return x.Latest
	}
	return 0
}

type ToastDndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Change        DndChange              `protobuf:"varint,1,opt,name=change,proto3,enum=rig.v1.DndChange" json:"change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastDndRequest) Reset() {
	*x = ToastDndRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastDndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastDndRequest) ProtoMessage() {}

func (x *ToastDndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastDndRequest.ProtoReflect.Descriptor instead.
func (*ToastDndRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{15}
}

func (x *ToastDndRequest) GetChange() DndChange {
	if x != nil {
		return x.Change
	}
	return DndChange_DND_CHANGE_UNSPECIFIED
}

type ToastDndResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	On    bool                   `protobuf:"varint,1,opt,name=on,proto3" json:"on,omitempty"`
	// Notifications filed and not drawn since Do Not Disturb last went on.
	Suppressed    uint32 `protobuf:"varint,2,opt,name=suppressed,proto3" json:"suppressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToastDndResponse) Reset() {
	*x = ToastDndResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToastDndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToastDndResponse) ProtoMessage() {}

func (x *ToastDndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToastDndResponse.ProtoReflect.Descriptor instead.
func (*ToastDndResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{16}
}

func (x *ToastDndResponse) GetOn() bool {
	if x != nil {
		return x.On
	}
	return false
}

func (x *ToastDndResponse) GetSuppressed() uint32 {
	if x != nil {
		return x.Suppressed
	}
	return 0
}

type SoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mute          SoundMute              `protobuf:"varint,1,opt,name=mute,proto3,enum=rig.v1.SoundMute" json:"mute,omitempty"`
	ReadAloud     ReadAloud              `protobuf:"varint,2,opt,name=read_aloud,json=readAloud,proto3,enum=rig.v1.ReadAloud" json:"read_aloud,omitempty"`
	ToastSound    ToastSound             `protobuf:"varint,3,opt,name=toast_sound,json=toastSound,proto3,enum=rig.v1.ToastSound" json:"toast_sound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoundRequest) Reset() {
	*x = SoundRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundRequest) ProtoMessage() {}

func (x *SoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundRequest.ProtoReflect.Descriptor instead.
func (*SoundRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{17}
}

func (x *SoundRequest) GetMute() SoundMute {
	if x != nil {
		return x.Mute
	}
	return SoundMute_SOUND_MUTE_UNSPECIFIED
}

func (x *SoundRequest) GetReadAloud() ReadAloud {
	if x != nil {
		return x.ReadAloud
	}
	return ReadAloud_READ_ALOUD_UNSPECIFIED
}

func (x *SoundRequest) GetToastSound() ToastSound {
	if x != nil {
		return x.ToastSound
	}
	return ToastSound_TOAST_SOUND_UNSPECIFIED
}

type SoundResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Muted      bool                   `protobuf:"varint,1,opt,name=muted,proto3" json:"muted,omitempty"`
	ReadAloud  ReadAloud              `protobuf:"varint,2,opt,name=read_aloud,json=readAloud,proto3,enum=rig.v1.ReadAloud" json:"read_aloud,omitempty"`
	ToastSound ToastSound             `protobuf:"varint,3,opt,name=toast_sound,json=toastSound,proto3,enum=rig.v1.ToastSound" json:"toast_sound,omitempty"`
	// rigd was given a sound file, so TOAST_SOUND_FILE is a choice.
	FileSet bool `protobuf:"varint,4,opt,name=file_set,json=fileSet,proto3" json:"file_set,omitempty"`
	// The player and the speech engine found; empty means none was.
	Player string `protobuf:"bytes,5,opt,name=player,proto3" json:"player,omitempty"`
	Engine string `protobuf:"bytes,6,opt,name=engine,proto3" json:"engine,omitempty"`
	// Why something is silent, in words; empty when nothing is.
	Problem       string `protobuf:"bytes,7,opt,name=problem,proto3" json:"problem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SoundResponse) Reset() {
	*x = SoundResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SoundResponse) ProtoMessage() {}

func (x *SoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SoundResponse.ProtoReflect.Descriptor instead.
func (*SoundResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{18}
}

func (x *SoundResponse) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

func (x *SoundResponse) GetReadAloud() ReadAloud {
	if x != nil {
		return x.ReadAloud
	}
	return ReadAloud_READ_ALOUD_UNSPECIFIED
}

func (x *SoundResponse) GetToastSound() ToastSound {
	if x != nil {
		return x.ToastSound
	}
	return ToastSound_TOAST_SOUND_UNSPECIFIED
}

func (x *SoundResponse) GetFileSet() bool {
	if x != nil {
		return x.FileSet
	}
	return false
}

func (x *SoundResponse) GetPlayer() string {
	if x != nil {
		return x.Player
	}
	return ""
}

func (x *SoundResponse) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *SoundResponse) GetProblem() string {
	if x != nil {
		return x.Problem
	}
	return ""
}

// SayRequest reads text aloud through the speech engine (S2), behind the
// mute. With wait, the answer comes once it has been heard, up to a bound.
type SayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Wait          bool                   `protobuf:"varint,2,opt,name=wait,proto3" json:"wait,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayRequest) Reset() {
	*x = SayRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayRequest) ProtoMessage() {}

func (x *SayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayRequest.ProtoReflect.Descriptor instead.
func (*SayRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{19}
}

func (x *SayRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SayRequest) GetWait() bool {
	if x != nil {
		return x.Wait
	}
	return false
}

type SayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// With wait: true once the line was heard, or dropped by a mute or a full
	// queue; false when the bound passed first.
	Heard         bool `protobuf:"varint,1,opt,name=heard,proto3" json:"heard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SayResponse) Reset() {
	*x = SayResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayResponse) ProtoMessage() {}

func (x *SayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayResponse.ProtoReflect.Descriptor instead.
func (*SayResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{20}
}

func (x *SayResponse) GetHeard() bool {
	if x != nil {
		return x.Heard
	}
	return false
}

var File_proto_rig_v1_registry_proto protoreflect.FileDescriptor

const file_proto_rig_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/rig/v1/registry.proto\x12\x06rig.v1\x1a\x17proto/rig/v1/wire.proto\"\xe3\x02\n" +
	"\aProgram\x12,\n" +
	"\bidentity\x18\x01 \x01(\v2\x10.rig.v1.IdentityR\bidentity\x12,\n" +
	"\bcoverage\x18\x02 \x01(\x0e2\x10.rig.v1.CoverageR\bcoverage\x12#\n" +
	"\rcoverage_note\x18\x03 \x01(\tR\fcoverageNote\x12#\n" +
	"\rsemantics_gen\x18\x04 \x01(\x05R\fsemanticsGen\x12\x1a\n" +
	"\bservices\x18\x05 \x03(\tR\bservices\x12\x16\n" +
	"\x06hosted\x18\x06 \x01(\bR\x06hosted\x12+\n" +
	"\bcommands\x18\a \x03(\v2\x0f.rig.v1.CommandR\bcommands\x12\x19\n" +
	"\bpane_url\x18\b \x01(\tR\apaneUrl\x12\x1a\n" +
	"\belements\x18\t \x03(\tR\belements\x12\x1a\n" +
	"\bpreamble\x18\n" +
	" \x01(\tR\bpreamble\"6\n" +
	"\x0fProgramsRequest\x12#\n" +
	"\x05depth\x18\x01 \x01(\x0e2\r.rig.v1.DepthR\x05depth\"?\n" +
	"\x10ProgramsResponse\x12+\n" +
	"\bprograms\x18\x01 \x03(\v2\x0f.rig.v1.ProgramR\bprograms\"\x0f\n" +
	"\rEstateRequest\"\xd6\x01\n" +
	"\x0eEstateResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04role\x18\x02 \x01(\x0e2\x12.rig.v1.EstateRoleR\x04role\x12%\n" +
	"\x0edaemon_version\x18\x03 \x01(\tR\rdaemonVersion\x12\x12\n" +
	"\x04wire\x18\x04 \x01(\tR\x04wire\x12#\n" +
	"\rsemantics_gen\x18\x05 \x01(\x05R\fsemanticsGen\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04root\x18\a \x01(\tR\x04root\"\xa1\x02\n" +
	"\x05Toast\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x1b\n" +
	"\trecord_id\x18\x02 \x01(\tR\brecordId\x12,\n" +
	"\bseverity\x18\x03 \x01(\x0e2\x10.rig.v1.SeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x16\n" +
	"\x06sender\x18\x06 \x01(\tR\x06sender\x12 \n" +
	"\fat_unix_nano\x18\a \x01(\x03R\n" +
	"atUnixNano\x12\x1e\n" +
	"\n" +
	"suppressed\x18\b \x01(\bR\n" +
	"suppressed\x12\x18\n" +
	"\areplies\x18\t \x03(\tR\areplies\x12\x1d\n" +
	"\n" +
	"reply_text\x18\n" +
	" \x01(\bR\treplyText\"\xb6\x01\n" +
	"\rNotifyRequest\x12,\n" +
	"\bseverity\x18\x01 \x01(\x0e2\x10.rig.v1.SeverityR\bseverity\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x18\n" +
	"\areplies\x18\x04 \x03(\tR\areplies\x12\x1d\n" +
	"\n" +
	"reply_text\x18\x05 \x01(\bR\treplyText\x12\x14\n" +
	"\x05speak\x18\x06 \x01(\tR\x05speak\"x\n" +
	"\x11ToastReplyRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x14\n" +
	"\x05reply\x18\x02 \x01(\tR\x05reply\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1c\n" +
	"\tdismissed\x18\x04 \x01(\bR\tdismissed\"A\n" +
	"\x12ToastReplyResponse\x12+\n" +
	"\x06answer\x18\x01 \x01(\v2\x13.rig.v1.ToastAnswerR\x06answer\"\xc0\x01\n" +
	"\vToastAnswer\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1a\n" +
	"\banswered\x18\x02 \x01(\bR\banswered\x12\x14\n" +
	"\x05reply\x18\x03 \x01(\tR\x05reply\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1c\n" +
	"\tdismissed\x18\x05 \x01(\bR\tdismissed\x12\x0e\n" +
	"\x02by\x18\x06 \x01(\tR\x02by\x12 \n" +
	"\fat_unix_nano\x18\a \x01(\x03R\n" +
	"atUnixNano\"P\n" +
	"\x12ToastAnswerRequest\x12\x1b\n" +
	"\trecord_id\x18\x01 \x01(\tR\brecordId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"B\n" +
	"\x13ToastAnswerResponse\x12+\n" +
	"\x06answer\x18\x01 \x01(\v2\x13.rig.v1.ToastAnswerR\x06answer\"5\n" +
	"\x0eNotifyResponse\x12#\n" +
	"\x05toast\x18\x01 \x01(\v2\r.rig.v1.ToastR\x05toast\"G\n" +
	"\x10ToastWaitRequest\x12\x14\n" +
	"\x05after\x18\x01 \x01(\x04R\x05after\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\rR\ttimeoutMs\"R\n" +
	"\x11ToastWaitResponse\x12%\n" +
	"\x06toasts\x18\x01 \x03(\v2\r.rig.v1.ToastR\x06toasts\x12\x16\n" +
	"\x06latest\x18\x02 \x01(\x04R\x06latest\"<\n" +
	"\x0fToastDndRequest\x12)\n" +
	"\x06change\x18\x01 \x01(\x0e2\x11.rig.v1.DndChangeR\x06change\"B\n" +
	"\x10ToastDndResponse\x12\x0e\n" +
	"\x02on\x18\x01 \x01(\bR\x02on\x12\x1e\n" +
	"\n" +
	"suppressed\x18\x02 \x01(\rR\n" +
	"suppressed\"\x9c\x01\n" +
	"\fSoundRequest\x12%\n" +
	"\x04mute\x18\x01 \x01(\x0e2\x11.rig.v1.SoundMuteR\x04mute\x120\n" +
	"\n" +
	"read_aloud\x18\x02 \x01(\x0e2\x11.rig.v1.ReadAloudR\treadAloud\x123\n" +
	"\vtoast_sound\x18\x03 \x01(\x0e2\x12.rig.v1.ToastSoundR\n" +
	"toastSound\"\xf1\x01\n" +
	"\rSoundResponse\x12\x14\n" +
	"\x05muted\x18\x01 \x01(\bR\x05muted\x120\n" +
	"\n" +
	"read_aloud\x18\x02 \x01(\x0e2\x11.rig.v1.ReadAloudR\treadAloud\x123\n" +
	"\vtoast_sound\x18\x03 \x01(\x0e2\x12.rig.v1.ToastSoundR\n" +
	"toastSound\x12\x19\n" +
	"\bfile_set\x18\x04 \x01(\bR\afileSet\x12\x16\n" +
	"\x06player\x18\x05 \x01(\tR\x06player\x12\x16\n" +
	"\x06engine\x18\x06 \x01(\tR\x06engine\x12\x18\n" +
	"\aproblem\x18\a \x01(\tR\aproblem\"4\n" +
	"\n" +
	"SayRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04wait\x18\x02 \x01(\bR\x04wait\"#\n" +
	"\vSayResponse\x12\x14\n" +
	"\x05heard\x18\x01 \x01(\bR\x05heard*V\n" +
	"\x05Depth\x12\x15\n" +
	"\x11DEPTH_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDEPTH_PROGRAMS\x10\x01\x12\x12\n" +
	"\x0eDEPTH_COMMANDS\x10\x02\x12\x0e\n" +
	"\n" +
	"DEPTH_FULL\x10\x03*{\n" +
	"\n" +
	"EstateRole\x12\x1b\n" +
	"\x17ESTATE_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ESTATE_ROLE_UNNAMED\x10\x01\x12\x1a\n" +
	"\x16ESTATE_ROLE_PRODUCTION\x10\x02\x12\x1b\n" +
	"\x17ESTATE_ROLE_DEVELOPMENT\x10\x03*\x8c\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSEVERITY_INFO\x10\x01\x12\x14\n" +
	"\x10SEVERITY_SUCCESS\x10\x02\x12\x14\n" +
	"\x10SEVERITY_WARNING\x10\x03\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x04\x12\x13\n" +
	"\x0fSEVERITY_URGENT\x10\x05*d\n" +
	"\tDndChange\x12\x1a\n" +
	"\x16DND_CHANGE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10DND_CHANGE_QUERY\x10\x01\x12\x11\n" +
	"\rDND_CHANGE_ON\x10\x02\x12\x12\n" +
	"\x0eDND_CHANGE_OFF\x10\x03*N\n" +
	"\tSoundMute\x12\x1a\n" +
	"\x16SOUND_MUTE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSOUND_MUTE_ON\x10\x01\x12\x12\n" +
	"\x0eSOUND_MUTE_OFF\x10\x02*p\n" +
	"\tReadAloud\x12\x1a\n" +
	"\x16READ_ALOUD_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eREAD_ALOUD_OFF\x10\x01\x12\x14\n" +
	"\x10READ_ALOUD_TITLE\x10\x02\x12\x1d\n" +
	"\x19READ_ALOUD_TITLE_AND_BODY\x10\x03*l\n" +
	"\n" +
	"ToastSound\x12\x1b\n" +
	"\x17TOAST_SOUND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TOAST_SOUND_HAIL\x10\x01\x12\x15\n" +
	"\x11TOAST_SOUND_BADGE\x10\x02\x12\x14\n" +
	"\x10TOAST_SOUND_FILE\x10\x03B?Z=github.com/borismilner/rig/proto/rig/v1/registryv1;registryv1b\x06proto3"

var (
	file_proto_rig_v1_registry_proto_rawDescOnce sync.Once
	file_proto_rig_v1_registry_proto_rawDescData []byte
)

func file_proto_rig_v1_registry_proto_rawDescGZIP() []byte {
	file_proto_rig_v1_registry_proto_rawDescOnce.Do(func() {
		file_proto_rig_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rig_v1_registry_proto_rawDesc), len(file_proto_rig_v1_registry_proto_rawDesc)))
	})
	return file_proto_rig_v1_registry_proto_rawDescData
}

var file_proto_rig_v1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_proto_rig_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_rig_v1_registry_proto_goTypes = []any{
	(Depth)(0),                  // 0: rig.v1.Depth
	(EstateRole)(0),             // 1: rig.v1.EstateRole
	(Severity)(0),               // 2: rig.v1.Severity
	(DndChange)(0),              // 3: rig.v1.DndChange
	(SoundMute)(0),              // 4: rig.v1.SoundMute
	(ReadAloud)(0),              // 5: rig.v1.ReadAloud
	(ToastSound)(0),             // 6: rig.v1.ToastSound
	(*Program)(nil),             // 7: rig.v1.Program
	(*ProgramsRequest)(nil),     // 8: rig.v1.ProgramsRequest
	(*ProgramsResponse)(nil),    // 9: rig.v1.ProgramsResponse
	(*EstateRequest)(nil),       // 10: rig.v1.EstateRequest
	(*EstateResponse)(nil),      // 11: rig.v1.EstateResponse
	(*Toast)(nil),               // 12: rig.v1.Toast
	(*NotifyRequest)(nil),       // 13: rig.v1.NotifyRequest
	(*ToastReplyRequest)(nil),   // 14: rig.v1.ToastReplyRequest
	(*ToastReplyResponse)(nil),  // 15: rig.v1.ToastReplyResponse
	(*ToastAnswer)(nil),         // 16: rig.v1.ToastAnswer
	(*ToastAnswerRequest)(nil),  // 17: rig.v1.ToastAnswerRequest
	(*ToastAnswerResponse)(nil), // 18: rig.v1.ToastAnswerResponse
	(*NotifyResponse)(nil),      // 19: rig.v1.NotifyResponse
	(*ToastWaitRequest)(nil),    // 20: rig.v1.ToastWaitRequest
	(*ToastWaitResponse)(nil),   // 21: rig.v1.ToastWaitResponse
	(*ToastDndRequest)(nil),     // 22: rig.v1.ToastDndRequest
	(*ToastDndResponse)(nil),    // 23: rig.v1.ToastDndResponse
	(*SoundRequest)(nil),        // 24: rig.v1.SoundRequest
	(*SoundResponse)(nil),       // 25: rig.v1.SoundResponse
	(*SayRequest)(nil),          // 26: rig.v1.SayRequest
	(*SayResponse)(nil),         // 27: rig.v1.SayResponse
	(*v1.Identity)(nil),         // 28: rig.v1.Identity
	(v1.Coverage)(0),            // 29: rig.v1.Coverage
	(*v1.Command)(nil),          // 30: rig.v1.Command
}
var file_proto_rig_v1_registry_proto_depIdxs = []int32{
	28, // 0: rig.v1.Program.identity:type_name -> rig.v1.Identity
	29, // 1: rig.v1.Program.coverage:type_name -> rig.v1.Coverage
	30, // 2: rig.v1.Program.commands:type_name -> rig.v1.Command
	0,  // 3: rig.v1.ProgramsRequest.depth:type_name -> rig.v1.Depth
	7,  // 4: rig.v1.ProgramsResponse.programs:type_name -> rig.v1.Program
	1,  // 5: rig.v1.EstateResponse.role:type_name -> rig.v1.EstateRole
	2,  // 6: rig.v1.Toast.severity:type_name -> rig.v1.Severity
	2,  // 7: rig.v1.NotifyRequest.severity:type_name -> rig.v1.Severity
	16, // 8: rig.v1.ToastReplyResponse.answer:type_name -> rig.v1.ToastAnswer
	16, // 9: rig.v1.ToastAnswerResponse.answer:type_name -> rig.v1.ToastAnswer
	12, // 10: rig.v1.NotifyResponse.toast:type_name -> rig.v1.Toast
	12, // 11: rig.v1.ToastWaitResponse.toasts:type_name -> rig.v1.Toast
	3,  // 12: rig.v1.ToastDndRequest.change:type_name -> rig.v1.DndChange
	4,  // 13: rig.v1.SoundRequest.mute:type_name -> rig.v1.SoundMute
	5,  // 14: rig.v1.SoundRequest.read_aloud:type_name -> rig.v1.ReadAloud
	6,  // 15: rig.v1.SoundRequest.toast_sound:type_name -> rig.v1.ToastSound
	5,  // 16: rig.v1.SoundResponse.read_aloud:type_name -> rig.v1.ReadAloud
	6,  // 17: rig.v1.SoundResponse.toast_sound:type_name -> rig.v1.ToastSound
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_rig_v1_registry_proto_init() }
func file_proto_rig_v1_registry_proto_init() {
	if File_proto_rig_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rig_v1_registry_proto_rawDesc), len(file_proto_rig_v1_registry_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rig_v1_registry_proto_goTypes,
		DependencyIndexes: file_proto_rig_v1_registry_proto_depIdxs,
		EnumInfos:         file_proto_rig_v1_registry_proto_enumTypes,
		MessageInfos:      file_proto_rig_v1_registry_proto_msgTypes,
	}.Build()
	File_proto_rig_v1_registry_proto = out.File
	file_proto_rig_v1_registry_proto_goTypes = nil
	file_proto_rig_v1_registry_proto_depIdxs = nil
}
