// The rig wire contract, major version 1: the registry and the estate.
//
// Part of proto package rig.v1 exactly as wire.proto is, so every message
// keeps its full name, its numbers and its bytes on the wire. It is a
// separate FILE only so its generated Go code is a separate package: a
// program links the handshake in wire.proto and none of this, and the
// window links this and none of verbs.proto. See wire.proto's header.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/rig/v1/registry.proto

package registryv1

import (
	v1 "github.com/borismilner/rig/proto/rig/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Depth is how much of the estate a read wants (section 9).
//
// Section 9's argument for four meta tools is a context budget: fifteen
// programs with twenty commands each is three hundred tools, and handing an
// agent all of it "destroys its context before it has done anything". So
// `list` "returns the estate at whatever depth is asked for".
//
// The line between the last two is one sentence: DEPTH_COMMANDS carries what
// an agent picks a command BY, DEPTH_FULL carries what it calls the command
// WITH. Scalars and the one-line summary are how you choose; schemas,
// examples, preconditions and prose are how you invoke.
type Depth int32

const (
	Depth_DEPTH_UNSPECIFIED Depth = 0
	// The estate itself: who is registered and how much of rig each has
	// adopted. No commands, no preamble.
	Depth_DEPTH_PROGRAMS Depth = 1
	// Every command's scalar properties and its summary - enough to choose
	// one, and nothing that costs a schema.
	Depth_DEPTH_COMMANDS Depth = 2
	// Everything this principal may see, preamble and argument schemas
	// included.
	Depth_DEPTH_FULL Depth = 3
)

// Enum value maps for Depth.
var (
	Depth_name = map[int32]string{
		0: "DEPTH_UNSPECIFIED",
		1: "DEPTH_PROGRAMS",
		2: "DEPTH_COMMANDS",
		3: "DEPTH_FULL",
	}
	Depth_value = map[string]int32{
		"DEPTH_UNSPECIFIED": 0,
		"DEPTH_PROGRAMS":    1,
		"DEPTH_COMMANDS":    2,
		"DEPTH_FULL":        3,
	}
)

func (x Depth) Enum() *Depth {
	p := new(Depth)
	*p = x
	return p
}

func (x Depth) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Depth) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[0].Descriptor()
}

func (Depth) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[0]
}

func (x Depth) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Depth.Descriptor instead.
func (Depth) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{0}
}

// EstateRole is what an estate is FOR.
//
// UNNAMED HAS A NUMBER OF ITS OWN AND THE ZERO IS NOT IT. proto3 cannot tell
// an unset scalar from a zero one, so a daemon that carries this field and
// fails to set it - a bug, or a build where the field landed and the setter
// did not - would render as "this is an unnamed estate" and an agent would
// branch on it. An unnamed estate reads as ephemeral and disposable and
// production does not, so the safe guess and the useful guess point opposite
// ways. Zero therefore keeps section 21's meaning, "nothing was said", and the
// identity fact gets a value of its own.
type EstateRole int32

const (
	EstateRole_ESTATE_ROLE_UNSPECIFIED EstateRole = 0 // nothing was said. Never a fact about an estate
	EstateRole_ESTATE_ROLE_UNNAMED     EstateRole = 1 // deliberately unnamed: a test, a build, an ephemeral run
	EstateRole_ESTATE_ROLE_PRODUCTION  EstateRole = 2
	EstateRole_ESTATE_ROLE_DEVELOPMENT EstateRole = 3
)

// Enum value maps for EstateRole.
var (
	EstateRole_name = map[int32]string{
		0: "ESTATE_ROLE_UNSPECIFIED",
		1: "ESTATE_ROLE_UNNAMED",
		2: "ESTATE_ROLE_PRODUCTION",
		3: "ESTATE_ROLE_DEVELOPMENT",
	}
	EstateRole_value = map[string]int32{
		"ESTATE_ROLE_UNSPECIFIED": 0,
		"ESTATE_ROLE_UNNAMED":     1,
		"ESTATE_ROLE_PRODUCTION":  2,
		"ESTATE_ROLE_DEVELOPMENT": 3,
	}
)

func (x EstateRole) Enum() *EstateRole {
	p := new(EstateRole)
	*p = x
	return p
}

func (x EstateRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EstateRole) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_rig_v1_registry_proto_enumTypes[1].Descriptor()
}

func (EstateRole) Type() protoreflect.EnumType {
	return &file_proto_rig_v1_registry_proto_enumTypes[1]
}

func (x EstateRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EstateRole.Descriptor instead.
func (EstateRole) EnumDescriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{1}
}

// Program is one program as one principal may see it (section 14).
//
// It is Declaration minus scope: what a reader is shown, not what was stored.
// Section 5k's rule that no surface may imply completeness is why coverage
// travels with it.
//
// THIS COMMENT USED TO SAY "minus preamble and scope", AND THAT WAS THE BUG.
// Section 9 requires the preamble to be "returned by describe on the program",
// and a program has been able to declare one since M1 - accepted at hello,
// validated, stored in the registry - with no message on any path able to
// carry it back. It was a dead field for as long as it existed. Scope stays
// out: it is how rig decides who may see this program, not something the
// program said about itself.
type Program struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Identity     *v1.Identity           `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Coverage     v1.Coverage            `protobuf:"varint,2,opt,name=coverage,proto3,enum=rig.v1.Coverage" json:"coverage,omitempty"`
	CoverageNote string                 `protobuf:"bytes,3,opt,name=coverage_note,json=coverageNote,proto3" json:"coverage_note,omitempty"`
	SemanticsGen int32                  `protobuf:"varint,4,opt,name=semantics_gen,json=semanticsGen,proto3" json:"semantics_gen,omitempty"`
	Services     []string               `protobuf:"bytes,5,rep,name=services,proto3" json:"services,omitempty"`
	Hosted       bool                   `protobuf:"varint,6,opt,name=hosted,proto3" json:"hosted,omitempty"`
	Commands     []*v1.Command          `protobuf:"bytes,7,rep,name=commands,proto3" json:"commands,omitempty"`
	// Where this program serves its own pane, validated at registration. A
	// reader gets it because the window is a reader like any other.
	PaneUrl string `protobuf:"bytes,8,opt,name=pane_url,json=paneUrl,proto3" json:"pane_url,omitempty"`
	// The kit elements this program declares (section 5h R3). A reader gets it
	// for the same reason it gets services: it is part of what the program said
	// about itself, not part of how anything draws it.
	Elements []string `protobuf:"bytes,9,rep,name=elements,proto3" json:"elements,omitempty"`
	// The one document an agent reads before touching this program (section 9).
	//
	// Carried at DEPTH_FULL only. It is prose, it can be long, and fifteen of
	// them in one list is the context cost section 9's whole tiering argument
	// exists to avoid - so it travels with describe and not with list.
	Preamble      string `protobuf:"bytes,10,opt,name=preamble,proto3" json:"preamble,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Program) Reset() {
	*x = Program{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Program) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Program) ProtoMessage() {}

func (x *Program) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Program.ProtoReflect.Descriptor instead.
func (*Program) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{0}
}

func (x *Program) GetIdentity() *v1.Identity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *Program) GetCoverage() v1.Coverage {
	if x != nil {
		return x.Coverage
	}
	return v1.Coverage(0)
}

func (x *Program) GetCoverageNote() string {
	if x != nil {
		return x.CoverageNote
	}
	return ""
}

func (x *Program) GetSemanticsGen() int32 {
	if x != nil {
		return x.SemanticsGen
	}
	return 0
}

func (x *Program) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *Program) GetHosted() bool {
	if x != nil {
		return x.Hosted
	}
	return false
}

func (x *Program) GetCommands() []*v1.Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *Program) GetPaneUrl() string {
	if x != nil {
		return x.PaneUrl
	}
	return ""
}

func (x *Program) GetElements() []string {
	if x != nil {
		return x.Elements
	}
	return nil
}

func (x *Program) GetPreamble() string {
	if x != nil {
		return x.Preamble
	}
	return ""
}

type ProgramsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// How much to say about each program. Absent means DEPTH_FULL, and that is
	// a COMPATIBILITY rule rather than a default worth having: every caller
	// written before this field existed asked for everything, and proto3 gives
	// it the zero value whether it says so or not. The kernel refuses an
	// unspecified depth outright (section 21's enum rule); the boundary is
	// where the old wire's meaning is restored, so exactly one place has to
	// know that the two disagree.
	Depth         Depth `protobuf:"varint,1,opt,name=depth,proto3,enum=rig.v1.Depth" json:"depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramsRequest) Reset() {
	*x = ProgramsRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramsRequest) ProtoMessage() {}

func (x *ProgramsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramsRequest.ProtoReflect.Descriptor instead.
func (*ProgramsRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{1}
}

func (x *ProgramsRequest) GetDepth() Depth {
	if x != nil {
		return x.Depth
	}
	return Depth_DEPTH_UNSPECIFIED
}

type ProgramsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Only what the calling principal may see. An unscoped, unprivileged client
	// gets nothing; a program gets itself; a client of the owner's gets all of
	// it, because introspect was decided when the connection was made.
	Programs      []*Program `protobuf:"bytes,1,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramsResponse) Reset() {
	*x = ProgramsResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramsResponse) ProtoMessage() {}

func (x *ProgramsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramsResponse.ProtoReflect.Descriptor instead.
func (*ProgramsResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{2}
}

func (x *ProgramsResponse) GetPrograms() []*Program {
	if x != nil {
		return x.Programs
	}
	return nil
}

type EstateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstateRequest) Reset() {
	*x = EstateRequest{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstateRequest) ProtoMessage() {}

func (x *EstateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstateRequest.ProtoReflect.Descriptor instead.
func (*EstateRequest) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{3}
}

type EstateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name this estate claimed, empty when it claimed none. Section 37's
	// precondition 6 makes it unique across the machine while it is held.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// ROLE IS DERIVED FROM name BY THE DAEMON, AT REPLY TIME, AND IS NEVER
	// STORED AND NEVER ACCEPTED AS INPUT. A client must never send one and must
	// never infer the other.
	//
	// Both are carried on purpose even though the name set is closed at two
	// today and role is therefore derivable. With only the name, the derivation
	// `name == "production"` would live in every consumer - every agent, every
	// script, outside this repository and uncountable - and reopening the set
	// would break all of them silently. Here it lives in the daemon, once, and
	// reopening the set breaks nothing. The two cannot disagree because there is
	// no second place to write one.
	Role EstateRole `protobuf:"varint,2,opt,name=role,proto3,enum=rig.v1.EstateRole" json:"role,omitempty"`
	// The daemon's own build. The same value `rig.ping` returns when it is
	// addressed to rig itself, consolidated here so one call answers "who did I
	// reach" rather than requiring a caller to know to probe "rig".
	DaemonVersion string `protobuf:"bytes,3,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	// The wire contract's major. Carried for completeness rather than for skew
	// detection: the major rides the proto package path, so a client and a
	// daemon on different majors cannot connect at all and major skew is
	// structurally impossible rather than undetected.
	Wire string `protobuf:"bytes,4,opt,name=wire,proto3" json:"wire,omitempty"`
	// RIG'S OWN SEMANTIC GENERATION, FROM ITS SELF-DECLARATION, AND IT IS NOT A
	// PER-PROGRAM SKEW DETECTOR. Do not read this as "have the programs I use
	// changed meaning". That question is per-program, its answer is already on
	// the wire in Program.semantics_gen and already readable, and what it needs
	// is a consumer on the capability map. This field answers only "what
	// semantics does the daemon itself implement", which is what a client built
	// from the development tree needs when it reaches the production daemon.
	SemanticsGen int32 `protobuf:"varint,5,opt,name=semantics_gen,json=semanticsGen,proto3" json:"semantics_gen,omitempty"`
	// THE INCARNATION, AS OPPOSED TO THE IDENTITY. Every other field in this
	// message is identical across a restart - same name, same role, same build,
	// same wire, same generation - so an agent holding a handle from before
	// could not tell "same rig, still up" from "same rig, restarted under me",
	// and a lease it believes it holds may already be somebody else's. This is
	// the only field here that moves, and a caller that remembers the last one
	// it saw gets the distinction for free.
	//
	// Bumped unconditionally on every start, with nothing consulted (section
	// 37, precondition 4, and V15): the cost of treating a planned restart as a
	// crash is one re-acquisition, and the cost of the reverse is a fencing
	// token that outlives what it fences.
	//
	// ZERO MEANS NO PERSISTENT STATE, WHICH IS AN ANSWER RATHER THAN A HOLE. An
	// estate started without a name opens no store, because it has no name to
	// key a subtree to, so it has no epoch to report. A real epoch is always at
	// least 1, because the store bumps before it publishes, so 0 is
	// unambiguously "this estate has no persistent state" and cannot be
	// confused with a real one.
	Epoch         uint64 `protobuf:"varint,6,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstateResponse) Reset() {
	*x = EstateResponse{}
	mi := &file_proto_rig_v1_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstateResponse) ProtoMessage() {}

func (x *EstateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstateResponse.ProtoReflect.Descriptor instead.
func (*EstateResponse) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_registry_proto_rawDescGZIP(), []int{4}
}

func (x *EstateResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EstateResponse) GetRole() EstateRole {
	if x != nil {
		return x.Role
	}
	return EstateRole_ESTATE_ROLE_UNSPECIFIED
}

func (x *EstateResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *EstateResponse) GetWire() string {
	if x != nil {
		return x.Wire
	}
	return ""
}

func (x *EstateResponse) GetSemanticsGen() int32 {
	if x != nil {
		return x.SemanticsGen
	}
	return 0
}

func (x *EstateResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_proto_rig_v1_registry_proto protoreflect.FileDescriptor

const file_proto_rig_v1_registry_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/rig/v1/registry.proto\x12\x06rig.v1\x1a\x17proto/rig/v1/wire.proto\"\xe3\x02\n" +
	"\aProgram\x12,\n" +
	"\bidentity\x18\x01 \x01(\v2\x10.rig.v1.IdentityR\bidentity\x12,\n" +
	"\bcoverage\x18\x02 \x01(\x0e2\x10.rig.v1.CoverageR\bcoverage\x12#\n" +
	"\rcoverage_note\x18\x03 \x01(\tR\fcoverageNote\x12#\n" +
	"\rsemantics_gen\x18\x04 \x01(\x05R\fsemanticsGen\x12\x1a\n" +
	"\bservices\x18\x05 \x03(\tR\bservices\x12\x16\n" +
	"\x06hosted\x18\x06 \x01(\bR\x06hosted\x12+\n" +
	"\bcommands\x18\a \x03(\v2\x0f.rig.v1.CommandR\bcommands\x12\x19\n" +
	"\bpane_url\x18\b \x01(\tR\apaneUrl\x12\x1a\n" +
	"\belements\x18\t \x03(\tR\belements\x12\x1a\n" +
	"\bpreamble\x18\n" +
	" \x01(\tR\bpreamble\"6\n" +
	"\x0fProgramsRequest\x12#\n" +
	"\x05depth\x18\x01 \x01(\x0e2\r.rig.v1.DepthR\x05depth\"?\n" +
	"\x10ProgramsResponse\x12+\n" +
	"\bprograms\x18\x01 \x03(\v2\x0f.rig.v1.ProgramR\bprograms\"\x0f\n" +
	"\rEstateRequest\"\xc2\x01\n" +
	"\x0eEstateResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04role\x18\x02 \x01(\x0e2\x12.rig.v1.EstateRoleR\x04role\x12%\n" +
	"\x0edaemon_version\x18\x03 \x01(\tR\rdaemonVersion\x12\x12\n" +
	"\x04wire\x18\x04 \x01(\tR\x04wire\x12#\n" +
	"\rsemantics_gen\x18\x05 \x01(\x05R\fsemanticsGen\x12\x14\n" +
	"\x05epoch\x18\x06 \x01(\x04R\x05epoch*V\n" +
	"\x05Depth\x12\x15\n" +
	"\x11DEPTH_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eDEPTH_PROGRAMS\x10\x01\x12\x12\n" +
	"\x0eDEPTH_COMMANDS\x10\x02\x12\x0e\n" +
	"\n" +
	"DEPTH_FULL\x10\x03*{\n" +
	"\n" +
	"EstateRole\x12\x1b\n" +
	"\x17ESTATE_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ESTATE_ROLE_UNNAMED\x10\x01\x12\x1a\n" +
	"\x16ESTATE_ROLE_PRODUCTION\x10\x02\x12\x1b\n" +
	"\x17ESTATE_ROLE_DEVELOPMENT\x10\x03B?Z=github.com/borismilner/rig/proto/rig/v1/registryv1;registryv1b\x06proto3"

var (
	file_proto_rig_v1_registry_proto_rawDescOnce sync.Once
	file_proto_rig_v1_registry_proto_rawDescData []byte
)

func file_proto_rig_v1_registry_proto_rawDescGZIP() []byte {
	file_proto_rig_v1_registry_proto_rawDescOnce.Do(func() {
		file_proto_rig_v1_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rig_v1_registry_proto_rawDesc), len(file_proto_rig_v1_registry_proto_rawDesc)))
	})
	return file_proto_rig_v1_registry_proto_rawDescData
}

var file_proto_rig_v1_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_rig_v1_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_rig_v1_registry_proto_goTypes = []any{
	(Depth)(0),               // 0: rig.v1.Depth
	(EstateRole)(0),          // 1: rig.v1.EstateRole
	(*Program)(nil),          // 2: rig.v1.Program
	(*ProgramsRequest)(nil),  // 3: rig.v1.ProgramsRequest
	(*ProgramsResponse)(nil), // 4: rig.v1.ProgramsResponse
	(*EstateRequest)(nil),    // 5: rig.v1.EstateRequest
	(*EstateResponse)(nil),   // 6: rig.v1.EstateResponse
	(*v1.Identity)(nil),      // 7: rig.v1.Identity
	(v1.Coverage)(0),         // 8: rig.v1.Coverage
	(*v1.Command)(nil),       // 9: rig.v1.Command
}
var file_proto_rig_v1_registry_proto_depIdxs = []int32{
	7, // 0: rig.v1.Program.identity:type_name -> rig.v1.Identity
	8, // 1: rig.v1.Program.coverage:type_name -> rig.v1.Coverage
	9, // 2: rig.v1.Program.commands:type_name -> rig.v1.Command
	0, // 3: rig.v1.ProgramsRequest.depth:type_name -> rig.v1.Depth
	2, // 4: rig.v1.ProgramsResponse.programs:type_name -> rig.v1.Program
	1, // 5: rig.v1.EstateResponse.role:type_name -> rig.v1.EstateRole
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_rig_v1_registry_proto_init() }
func file_proto_rig_v1_registry_proto_init() {
	if File_proto_rig_v1_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rig_v1_registry_proto_rawDesc), len(file_proto_rig_v1_registry_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_rig_v1_registry_proto_goTypes,
		DependencyIndexes: file_proto_rig_v1_registry_proto_depIdxs,
		EnumInfos:         file_proto_rig_v1_registry_proto_enumTypes,
		MessageInfos:      file_proto_rig_v1_registry_proto_msgTypes,
	}.Build()
	File_proto_rig_v1_registry_proto = out.File
	file_proto_rig_v1_registry_proto_goTypes = nil
	file_proto_rig_v1_registry_proto_depIdxs = nil
}
