#!/usr/bin/env python3
"""Inline theme.js and app.js into one self-contained page.

Chrome refuses to fetch an ES module over file://, so a page meant to be
opened by double-clicking cannot have external module scripts. The sources
stay separate files (they are the ones worth reading and diffing); this
produces the artefact.

    python3 design/build.py        # -> design/visual-system.html
"""
import re, pathlib, sys

HERE = pathlib.Path(__file__).parent
src   = (HERE / "visual-system.src.html").read_text(encoding="utf-8")
theme = (HERE / "theme.js").read_text(encoding="utf-8")
app   = (HERE / "app.js").read_text(encoding="utf-8")

# strip module syntax: exports become plain declarations, the import goes
theme = re.sub(r"^export\s+", "", theme, flags=re.M)
app   = re.sub(r"^import\s+\{[^}]*\}\s+from\s+'\./theme\.js';\s*$", "", app, flags=re.M)

bundle = (
    "/* generated by design/build.py from theme.js + app.js - edit those */\n"
    "(function(){\n" + theme + "\n" + app + "\n})();"
)

# NOTE: the replacement MUST be a function. As a string, re.subn would
# interpret backslash escapes inside the JavaScript - \n in a string literal
# becomes a real newline and the bundle stops parsing.
tag = "<script>\n" + bundle.replace("</script>", "<\\/script>") + "\n</script>"
out, n = re.subn(
    r'<script type="module" src="\./app\.js"></script>',
    lambda m: tag,
    src,
)
if n != 1:
    sys.exit("build: script placeholder not found exactly once (found %d)" % n)

(HERE / "visual-system.html").write_text(out, encoding="utf-8")
print("built design/visual-system.html  (%d KB)" % (len(out) // 1024))
