#!/usr/bin/env python3
"""Inline theme.js and mock.js into one page that opens by double-click.

Chrome refuses an ES module over file://, as design/build.py says, so the
sources stay separate and this writes the artefact.

    python3 design/dashboard/build.py   # -> design/dashboard/dashboard.html
"""
import pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).parent
src = (HERE / "dashboard.src.html").read_text(encoding="utf-8")
theme = (HERE.parent / "theme.js").read_text(encoding="utf-8")
mock = (HERE / "mock.js").read_text(encoding="utf-8")

theme = re.sub(r"^export\s+", "", theme, flags=re.M)
mock, n = re.subn(r"^import\s+\{[^}]*\}\s+from\s+'\.\./theme\.js';\s*$", "", mock, flags=re.M)
if n != 1:
    sys.exit("build: mock.js does not import theme.js exactly once (found %d)" % n)

bundle = ("/* generated by design/dashboard/build.py from theme.js + mock.js"
          " - edit those */\n(function(){\n" + theme + "\n" + mock + "\n})();")
check = subprocess.run(["node", "--check", "-"], input=bundle, capture_output=True, text=True)
if check.returncode != 0:
    sys.exit("build: the script does not parse\n" + (check.stderr or check.stdout).rstrip())

tag = "<script>\n" + bundle.replace("</script>", "<\\/script>") + "\n</script>"
out, n = re.subn(r'<script type="module" src="\./mock\.js"></script>', lambda m: tag, src)
if n != 1:
    sys.exit("build: script placeholder not found exactly once (found %d)" % n)
(HERE / "dashboard.html").write_text(out, encoding="utf-8")
print("built design/dashboard/dashboard.html (%d KB)" % (len(out) // 1024))
