#!/usr/bin/env python3
"""Inline theme.js, rig-kit.js, mock.js and Ledger's GUI into one page that
opens by double-click.

Chrome refuses an ES module over file://, as design/build.py says, so the
sources stay separate and this writes the artefact.

    python3 design/dashboard/build.py   # -> design/dashboard/dashboard.html
    python3 design/dashboard/build.py --gui-out X.html   # also Ledger's GUI alone,
                                                         # for the contrast gate
"""
import json, pathlib, re, subprocess, sys

HERE = pathlib.Path(__file__).parent
src = (HERE / "dashboard.src.html").read_text(encoding="utf-8")
theme = (HERE.parent / "theme.js").read_text(encoding="utf-8")
mock = (HERE / "mock.js").read_text(encoding="utf-8")
kit = (HERE / "rig-kit.js").read_text(encoding="utf-8")
gui = (HERE / "ledger-gui.html").read_text(encoding="utf-8")

theme = re.sub(r"^export\s+", "", theme, flags=re.M)
kit = re.sub(r"^export\s+", "", kit, flags=re.M)
mock, n = re.subn(r"^import\s+\{[^}]*\}\s+from\s+'\./rig-kit\.js';\s*$", "", mock, flags=re.M)
if n != 1:
    sys.exit("build: mock.js does not import rig-kit.js exactly once (found %d)" % n)
selfdecl = (HERE / "rig-self.json").read_text(encoding="utf-8")
schema = (HERE.parent.parent / "internal" / "config" / "schema.json").read_text(encoding="utf-8")
for token, body in (("__RIG_SELF__", selfdecl), ("__RIG_SCHEMA__", schema)):
    mock, n = re.subn(token, lambda m: json.dumps(json.loads(body)), mock)
    if n != 1:
        sys.exit("build: %s not found exactly once (found %d)" % (token, n))
mock, n = re.subn(r"__LEDGER_GUI__", lambda m: json.dumps(gui), mock)
if n != 1:
    sys.exit("build: __LEDGER_GUI__ not found exactly once (found %d)" % n)
mock, n = re.subn(r"^import\s+\{[^}]*\}\s+from\s+'\.\./theme\.js';\s*$", "", mock, flags=re.M)
if n != 1:
    sys.exit("build: mock.js does not import theme.js exactly once (found %d)" % n)

bundle = ("/* generated by design/dashboard/build.py from theme.js, rig-kit.js, mock.js"
          " - edit those */\n(function(){\n" + theme + "\n" + kit + "\n" + mock + "\n})();")
check = subprocess.run(["node", "--check", "-"], input=bundle, capture_output=True, text=True)
if check.returncode != 0:
    sys.exit("build: the script does not parse\n" + (check.stderr or check.stdout).rstrip())

tag = "<script>\n" + bundle.replace("</script>", "<\\/script>") + "\n</script>"
out, n = re.subn(r'<script type="module" src="\./mock\.js"></script>', lambda m: tag, src)
if n != 1:
    sys.exit("build: script placeholder not found exactly once (found %d)" % n)
(HERE / "dashboard.html").write_text(out, encoding="utf-8")
print("built design/dashboard/dashboard.html (%d KB)" % (len(out) // 1024))

# Ledger's GUI alone, as rig would serve it, so the contrast gate can measure
# what lands inside the frame (it does not look into frames).
if "--gui-out" in sys.argv:
    out_path = pathlib.Path(sys.argv[sys.argv.index("--gui-out") + 1])
    js = theme + "\n" + kit + """
const seed = { statement: 'September statement', entries: 418, matched: 412, lastRun: '10:40', running: 0.5,
  open: [{ id: 1182, date: '09-14', payee: 'Hetzner Online', amount: '-38.20', bank: 'HETZNER ONLINE GMBH 38.20', why: 'same amount twice', sev: 'warning' },
         { id: 1201, date: '09-22', payee: 'Cafe Neko', amount: '-6.40', bank: '', why: 'no bank line', sev: 'error' }],
  done: [{ id: 1183, at: '10:41', what: 'matched', sev: 'success' }, { id: 1190, at: '10:42', what: 'not a match, kept open in the books', sev: 'info' }] };
process.stdout.write(guiDoc(rigCss(tokens(DEFAULTS, 'dark'), tokens(DEFAULTS, 'light')), GUI, 'dark', seed));
"""
    r = subprocess.run(["node", "-e", "const GUI = " + json.dumps(gui) + ";\n" + js], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("build: the GUI page did not build\n" + r.stderr)
    out_path.write_text(r.stdout, encoding="utf-8")
    print("built %s" % out_path)
