#!/usr/bin/env python3
"""Split a big logbook file into one file per entry, and keep the old path as
a generated index (plan/51, ruled by Boris 2026-10-01: the files stay the
truth, and an agent reads the entry it needs instead of the whole file).

THE MODEL. A document is an ordered list of parts, one file each, named
NNNN-slug.md. Concatenating the parts in name order gives back the original
document byte for byte. A part over BIG bytes becomes a directory of its own
parts, split at its `###` headings, or failing those at its table rows, so a
200-row table is 200 small files plus one that carries the header.

    DECISIONS.md           generated index: one line per entry
    decisions/0001-what-rig-is.md
    decisions/0248-the-logbook-files-stay-the-truth.md

WHAT PROVES NOTHING WAS LOST. `split` reassembles the parts in memory and
compares them with the original before writing anything, then reads the
written files back and compares again. `check` says whether the index is
current.

ADDING AN ENTRY NEEDS NO READ. Create the next NNNN-slug.md, or append a
`## ` section below the marker at the end of the index the old way, and run
`index`: whatever sits below the marker is moved into new parts first. Two
agents picking the same number both keep their files; order then falls to
the slug.

    python3 tools/logsplit.py split DECISIONS.md     # once: file -> parts
    python3 tools/logsplit.py index DECISIONS.md     # regenerate the index
    python3 tools/logsplit.py check DECISIONS.md     # exit 1 if stale
    python3 tools/logsplit.py cat DECISIONS.md       # the whole document

Needs nothing but Python: rig being down never stops it (plan/51 R3).
"""
import os, re, sys

BIG = 24 * 1024
# The index tells its reader where this tool is, since it lives in another repo.
TOOL = os.path.abspath(__file__).replace(os.path.expanduser("~"), "~", 1)
MARK = "<!-- logsplit: add an entry below this line, or as a new file in {dir}/; then run python3 " + TOOL + " index {name} -->"
HEAD = "<!-- generated by tools/logsplit.py from {dir}/ - edit the parts, not this index -->"


def slug(title):
    t = re.sub(r"[`*_\[\]()~⛔✅]", "", title.lower())
    t = re.sub(r"[^a-z0-9]+", "-", t).strip("-")
    return (t[:60].rstrip("-")) or "part"


def cut(text, pattern):
    """Split text before each line matching pattern; the first piece is what
    precedes the first match (possibly empty)."""
    idx = [m.start() for m in re.finditer(pattern, text, re.M)]
    if not idx:
        return [text]
    bounds = [0] + idx + [len(text)]
    return [text[a:b] for a, b in zip(bounds, bounds[1:])]


def rows(text):
    """Split before every table row after the first table's separator, so a
    row wrapped by a stray line still gets its own piece. Piece 0 is what
    precedes the first row; a later table's header and any prose ride with
    the row before them."""
    lines = text.splitlines(keepends=True)
    cuts, in_table = [], False
    for i, ln in enumerate(lines):
        if re.match(r"^\|\s*:?-{3,}", ln) and i and lines[i - 1].startswith("|"):
            in_table = True
            continue
        header = i + 1 < len(lines) and re.match(r"^\|\s*:?-{3,}", lines[i + 1])
        if in_table and ln.startswith("|") and not header:
            cuts.append(i)
    if len(cuts) < 2:
        return [text]
    bounds = [0] + cuts + [len(lines)]
    return ["".join(lines[a:b]) for a, b in zip(bounds, bounds[1:]) if a < b]


def title_of(part):
    lines = [l for l in part.splitlines() if l.strip() and not re.match(r"^\s*[-=]{20,}\s*$", l)]
    first = lines[0].strip() if lines else ""
    if first.startswith("|"):
        cells = [c.strip() for c in first.strip("|").split("|")]
        return " - ".join(c for c in cells[:2] if c)
    return re.sub(r"^#+\s*", "", first)


def paragraphs(text, size=BIG // 2):
    """Pack blank-line-separated paragraphs into pieces of about size bytes:
    the last resort for prose with no headings and no tables."""
    paras = re.split(r"(?<=\n\n)", text)
    out, cur = [], ""
    for p in paras:
        if cur and len(cur) + len(p) > size:
            out.append(cur)
            cur = ""
        cur += p
    if cur:
        out.append(cur)
    return out


# A heading, by format: markdown's `## `, or the banner a .txt file uses
# (a dashed rule, a title line, a dashed rule).
HEADINGS = {".md": lambda level: r"^#{%d} " % level,
            ".txt": lambda level: r"^-{20,}\n(?=[^\n]+\n-{20,}\n)" if level == 2 else r"(?!)"}


def plan(text, level=2, ext=".md"):
    """The parts of text: a list of (name, content | sublist). A part over
    BIG splits at its next heading level, then at table rows, then at
    paragraphs."""
    pieces = [p for p in cut(text, HEADINGS[ext](level)) if p]
    if level > 2 and len(pieces) == 1:
        pieces = rows(text)
    if level > 2 and len(pieces) == 1 and len(text) > BIG:
        pieces = paragraphs(text)
    out = []
    for n, p in enumerate(pieces):
        name = "%04d-%s" % (n, slug(title_of(p)) if n else "about")
        if len(p) > BIG and level < 5:
            sub = plan(p, level + 1, ext)
            if len(sub) > 1:
                out.append((name, sub))
                continue
        out.append((name, p))
    return out


def join(parts):
    return "".join(join(c) if isinstance(c, list) else c for _, c in parts)


def load(d):
    """Read a parts directory back: (name, content | sublist), name order."""
    out = []
    for e in sorted(os.listdir(d)):
        p = os.path.join(d, e)
        if os.path.isdir(p):
            out.append((e, load(p)))
        elif e.endswith(".md") and re.match(r"^\d{4}-", e):
            out.append((e[:-3], open(p, encoding="utf-8").read()))
    return out


def write(d, parts):
    os.makedirs(d, exist_ok=True)
    for name, c in parts:
        if isinstance(c, list):
            write(os.path.join(d, name), c)
        else:
            with open(os.path.join(d, name + ".md"), "w", encoding="utf-8") as f:
                f.write(c)


def paths(doc):
    base = os.path.dirname(os.path.abspath(doc))
    name = os.path.basename(doc)
    stem = name.rsplit(".", 1)[0].lower()
    return base, name, stem, os.path.join(base, stem)


def index_text(name, stem, parts):
    lines = [HEAD.format(dir=stem), ""]
    about = parts[0][1] if parts and parts[0][0].startswith("0000-about") else ""
    if isinstance(about, str) and about:
        lines += [about.rstrip("\n"), ""]
    lines += ["**One file per entry, in `%s/`.** Read the entry you need; "
              "`grep -r` the folder; `python3 %s cat %s` gives the whole "
              "document. Sizes are in KB." % (stem, TOOL, name), ""]

    def walk(ps, rel, depth):
        for pname, c in ps:
            if depth == 0 and pname.startswith("0000-about") and isinstance(c, str):
                continue  # shown inline above
            size = len(join(c) if isinstance(c, list) else c) / 1024
            t = title_of(join(c) if isinstance(c, list) else c)
            t = (t[:110] + "...") if len(t) > 113 else t
            link = rel + "/" + pname + ("/" if isinstance(c, list) else ".md")
            lines.append("%s- [%s](%s) %s (%.1f)" % ("  " * depth, pname[:4], link, t, size))
            if isinstance(c, list):
                walk(c, rel + "/" + pname, depth + 1)

    walk(parts, stem, 0)
    lines += ["", MARK.format(dir=stem, name=name), ""]
    return "\n".join(lines)


def absorb(doc, d, stem, name):
    """Move whatever sits below the marker in the index into new parts."""
    text = open(doc, encoding="utf-8").read()
    # Matched by its prefix, so a marker an older version wrote still guards
    # what was appended below it.
    m = re.search(r"^<!-- logsplit: add an entry below this line.*-->$", text, re.M)
    if not m:
        if text.startswith(HEAD.format(dir=stem)):
            return 0
        raise SystemExit("%s has no marker and is not a generated index: nothing touched" % name)
    tail = text[m.end():].strip("\n")
    if not tail:
        return 0
    have = [e for e in os.listdir(d) if re.match(r"^\d{4}-", e)]
    n = max(int(e[:4]) for e in have) + 1 if have else 1
    added = 0
    for p in cut(tail + "\n", r"^## "):
        if not p.strip():
            continue
        if not p.endswith("\n\n"):
            p = p.rstrip("\n") + "\n\n"
        with open(os.path.join(d, "%04d-%s.md" % (n, slug(title_of(p)))), "w", encoding="utf-8") as f:
            f.write(p)
        n += 1
        added += 1
    return added


def main(argv):
    if len(argv) != 3 or argv[1] not in ("split", "index", "check", "cat"):
        print(__doc__.split("\n\n")[-2])
        return 2
    cmd, doc = argv[1], argv[2]
    base, name, stem, d = paths(doc)
    if cmd == "split":
        if os.path.exists(d):
            print("%s/ exists: already split; use index" % stem)
            return 1
        text = open(doc, encoding="utf-8").read()
        parts = plan(text, ext=os.path.splitext(name)[1] or ".md")
        if join(parts) != text:
            print("reassembly differs from %s: nothing written" % name)
            return 1
        write(d, parts)
        if join(load(d)) != text:
            print("parts on disk do not reassemble to %s: left %s/ for inspection" % (name, stem))
            return 1
        with open(doc, "w", encoding="utf-8") as f:
            f.write(index_text(name, stem, load(d)))
        print("%s: %d bytes -> %s/ (%d top-level parts); index %d bytes"
              % (name, len(text), stem, len(parts), os.path.getsize(doc)))
        return 0
    if not os.path.isdir(d):
        print("%s/ does not exist: run split first" % stem)
        return 1
    if cmd == "cat":
        sys.stdout.write(join(load(d)))
        return 0
    if cmd == "index":
        added = absorb(doc, d, stem, name)
        with open(doc, "w", encoding="utf-8") as f:
            f.write(index_text(name, stem, load(d)))
        print("%s: index rebuilt%s" % (name, ", %d entries moved in from below the marker" % added if added else ""))
        return 0
    want = index_text(name, stem, load(d))
    have = open(doc, encoding="utf-8").read()
    if have != want:
        print("%s is stale against %s/: run python3 %s index %s" % (name, stem, TOOL, name))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
