#!/usr/bin/env python3
"""Split PLAN.md into plan/NN-slug.md, one file per numbered section, and keep
PLAN.md as the generated index.

WHY PLAN.md STAYS. Roughly 370 citations across the logbook and the source say
"PLAN.md section 37" or "PLAN.md ss37". They cite by SECTION NUMBER, never by
line, so an index at the old path keeps every one of them resolving: a reader
opens PLAN.md, reads the row for 37, and goes to the file. Deleting PLAN.md
would have broken all of them at once; this breaks none.

WHAT PROVES NOTHING WAS LOST. Every split reassembles the parts in memory and
compares them to the original body byte for byte before writing anything. A
mismatch aborts with nothing touched. That check is the whole reason this is a
script rather than an afternoon of careful editing.

    python3 tools/plansplit.py            # split, or re-split after edits
    python3 tools/plansplit.py --check    # exit 1 if the index or parts are stale

cmd/depscheck needs no change: it finds "## 22. Tech stack" and reads to the
next "## " or to EOF, which is exactly what its own file gives it.
"""
import os, re, sys

PLAN, DIR = "PLAN.md", "plan"
MARK = "<!-- generated by tools/plansplit.py -->"
GROUPS = [("WHAT IT IS - read before proposing anything", 1, 4),
          ("HOW IT IS BUILT - the specification proper", 5, 22),
          ("THE ROUTE - order, gates, and what is refused", 23, 30),
          ("THE RECORD - what changed and why. **CHANGELOG, not specification**", 31, 38),
          ("ADDED SINCE THE SPLIT - specification, not changelog", 39, 99)]


def slug(n, title):
    w = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-")
    while len(w) > 40:
        w = w.rsplit("-", 1)[0]
    return f"{n:02d}-{w}.md"


def parse(text):
    """-> (preamble_lines, [(n, title, slug, body_lines)]). Body includes its heading."""
    lines = text.split("\n")
    heads = []
    for i, l in enumerate(lines):
        if l.startswith("## "):
            m = re.match(r"(\d+)\.\s*(.+)", l[3:].strip())
            if m:
                heads.append((i, int(m.group(1)), m.group(2).strip()))
    if not heads:
        sys.exit(f"{PLAN}: no numbered sections found")
    secs = []
    for k, (i, n, title) in enumerate(heads):
        end = heads[k + 1][0] if k + 1 < len(heads) else len(lines)
        secs.append((n, title, slug(n, title), lines[i:end]))
    return lines[:heads[0][0]], secs


def index(pre, secs):
    """The new PLAN.md: the original front matter, then the generated index."""
    keep = []
    for l in pre:
        if l.startswith("## Map"):
            break
        keep.append(l)
    # Normalise the tail so the generator converges: a re-run reads back its own
    # "---" separator, and without this the file grows one rule per run.
    while keep and (not keep[-1].strip() or keep[-1].strip() == "---"):
        keep.pop()
    total = sum(len(b) for _, _, _, b in secs) + len(keep)
    changelog = sum(len(b) for n, _, _, b in secs if n >= 31)
    o = keep + ["", "---", "", MARK, "",
        "## Map - this file is the INDEX. The sections live in `plan/`.",
        "",
        f"**The specification is {total} lines across {len(secs)} files and nobody reads it",
        "whole.** It is a reference to query, and it is queried with two questions:",
        '*"what is rig supposed to do"* and *"what did he already rule on this"*.',
        "**This index exists so a requirement cannot hide**, which is the failure this",
        "project has had four times - the tray icon, the acceptance floor, the readiness",
        "bar, and the successor clause.",
        "",
        "**A citation of the form `PLAN.md section 37` still resolves.** Sections are",
        "cited by NUMBER everywhere in this project, never by line, so the number is the",
        "address and this table is where it is looked up.",
        "",
        "**GENERATED. Do not hand-edit this file, and do not add a section body to it** -",
        "run `python3 tools/plansplit.py`. Every split proves the parts reassemble into",
        "the original byte for byte before writing anything.",
        ""]
    for title, a, b in GROUPS:
        sel = [s for s in secs if a <= s[0] <= b]
        if not sel:
            continue
        o += [f"### {title}", "", "| § | Section | Lines | File |", "|---|---|---|---|"]
        o += [f"| {n} | {t} | {len(bd)} | [`plan/{sl}`]({DIR}/{sl}) |" for n, t, sl, bd in sel]
        o.append("")
    o += ["### The four questions a seat actually arrives with", "",
        "| Asking | Go to |", "|---|---|",
        "| **what should I build next?** | **NOT here.** `logbook/projects/rig/BACKLOG.md` answers WHAT NEXT; this answers WHAT IS IT |",
        "| **how much longer until rig develops rig?** | `logbook/projects/rig/READINESS.txt`, and nothing else may answer it |",
        "| **what do agents get, and when?** | §16 for the coordination primitives, **§39 for the continuity record**, §37 for the minimum set and the staged migration |",
        "| **has he already ruled on this?** | `logbook/projects/rig/DECISIONS.md` first, then §31-38. **Grep before proposing** - proposing what already exists is this project's named failure mode |",
        "",
        f"**§31-38 ARE A CHANGELOG INSIDE A SPECIFICATION** - {changelog} of {total} lines,",
        f"{round(100 * changelog / total)}%. Splitting the file did not fix that; it made it visible and",
        "cheap to act on, since those eight sections are now eight files that can move to",
        "the logbook in one commit. `BACKLOG.md` B24. **Until they do, a reader after the",
        "current rule prefers the numbered section over the pass that changed it.**", ""]
    return o


def current(secs):
    """What is on disk now, as {filename: lines}."""
    out = {}
    if os.path.isdir(DIR):
        for f in sorted(os.listdir(DIR)):
            if f.endswith(".md"):
                out[f] = open(os.path.join(DIR, f)).read().split("\n")
    return out


def main():
    text = open(PLAN).read()
    if MARK in text:                       # already split: rebuild from the parts
        # Do NOT parse() here - PLAN.md is the index now and has no numbered
        # sections of its own, which is exactly what parse() refuses to accept.
        keep = []
        for l in text.split("\n"):
            if l.startswith("## Map") or l == MARK:
                break
            keep.append(l)
        secs = []
        for f in sorted(os.listdir(DIR)):
            if not f.endswith(".md"):
                continue
            body = open(os.path.join(DIR, f)).read().split("\n")  # no rstrip: see above
            m = re.match(r"## (\d+)\.\s*(.+)", body[0])
            if not m:
                sys.exit(f"{DIR}/{f}: first line is not a numbered section heading")
            secs.append((int(m.group(1)), m.group(2).strip(), f, body))
        secs.sort()
        for n, t, f, _ in secs:
            if f != slug(n, t):
                sys.exit(f"{DIR}/{f}: heading says it should be named {slug(n, t)}")
        new_index = index(keep, secs)
    else:                                  # first split: carve PLAN.md up
        pre, secs = parse(text)
        body = []
        for _, _, _, b in secs:
            body += b
        if pre + body != text.split("\n"):
            sys.exit("ABORT: reassembly does not match the original. Nothing written.")
        print(f"round-trip OK: {len(secs)} sections, {len(body)} body lines reassemble exactly")
        os.makedirs(DIR, exist_ok=True)
        for n, t, sl, b in secs:
            # VERBATIM. No rstrip: a section's trailing blank lines are part of it,
            # and stripping them cost 38 lines on the first attempt - caught by the
            # from-disk round trip, which the in-memory one structurally cannot see.
            open(os.path.join(DIR, sl), "w").write("\n".join(b))
        new_index = index(pre, secs)

    out = "\n".join(new_index).rstrip("\n") + "\n"
    if out == open(PLAN).read():
        print("index is current")
        return
    if "--check" in sys.argv:
        sys.exit("index is STALE - run: python3 tools/plansplit.py")
    open(PLAN, "w").write(out)
    print(f"PLAN.md is now the index: {len(new_index)} lines over {len(secs)} section files")


main()
