package analysis_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/boris-milner/rig/internal/analysis"
)

// A gate that cannot fail is what PLAN.md section 5i says the previous
// modularity rules were, so every case here is a violation the analyzer has to
// catch, paired with the nearby thing it must not catch.

// tree writes files into a scratch module and runs one analyzer over it.
// Paths are relative, and they matter: Product() reads them.
func run(t *testing.T, a analysis.Analyzer, files map[string]string) (int, string) {
	t.Helper()
	dir := t.TempDir()
	for name, body := range files {
		p := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	var out, errs strings.Builder
	code, err := analysis.Run(a, []string{dir}, &out, &errs)
	if err != nil {
		t.Fatalf("run: %v", err)
	}
	return code, out.String() + errs.String()
}

func wantFail(t *testing.T, code int, out, substr string) {
	t.Helper()
	if code == 0 {
		t.Fatalf("wanted a failure, got a pass.\n%s", out)
	}
	if !strings.Contains(out, substr) {
		t.Fatalf("wanted %q in the report, got:\n%s", substr, out)
	}
}

func wantPass(t *testing.T, code int, out string) {
	t.Helper()
	if code != 0 {
		t.Fatalf("wanted a pass, got a failure:\n%s", out)
	}
}

func TestNoProgramIDCatchesALiteral(t *testing.T) {
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\nvar route = \"shelf\"\n",
	})
	wantFail(t, code, out, `names the in-house program "shelf"`)
}

func TestNoProgramIDCatchesADottedMethod(t *testing.T) {
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\nvar m = \"grabbit.reindex\"\n",
	})
	wantFail(t, code, out, `names the in-house program "grabbit"`)
}

func TestNoProgramIDCatchesAnIdentityBranch(t *testing.T) {
	// The name on the right is one rig has never heard of: the shape is the
	// violation, which is what makes this more than a deny list.
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\nfunc f(programID string) bool {\n" +
			"\treturn programID == \"something-new\"\n}\n",
	})
	wantFail(t, code, out, `compared against the literal "something-new"`)
}

func TestNoProgramIDCatchesAnIdentitySwitch(t *testing.T) {
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\nfunc f(program string) int {\n" +
			"\tswitch program {\n\tcase \"whatever\":\n\t\treturn 1\n\t}\n\treturn 0\n}\n",
	})
	wantFail(t, code, out, `has the case "whatever"`)
}

func TestNoProgramIDAllowsRigsOwnNamespace(t *testing.T) {
	// The daemon has to name the ids it reserves in order to refuse them.
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\nfunc f(program string) bool {\n" +
			"\treturn program == \"rig\" || program == \"\"\n}\n",
	})
	wantPass(t, code, out)
}

func TestNoProgramIDAllowsAWordThatIsNotAnID(t *testing.T) {
	// "dispatch" is both a program and an ordinary verb. An error prefix is
	// not an identity, and the dot rule is what tells them apart.
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\nimport \"errors\"\n\n" +
			"var errFoo = errors.New(\"dispatch: the frame was refused\")\n",
	})
	wantPass(t, code, out)
}

func TestNoProgramIDSkipsTestsSoThePilotCanRun(t *testing.T) {
	// Section 20 has CI running the real shelf binary against rig.
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a_test.go": "package svc\n\nvar pilot = \"shelf\"\n",
	})
	wantPass(t, code, out)
}

func TestNoProgramIDSkipsGeneratedCode(t *testing.T) {
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.pb.go": "// Code generated by protoc-gen-go. DO NOT EDIT.\n\n" +
			"package svc\n\nvar x = \"shelf\"\n",
	})
	wantPass(t, code, out)
}

func TestADirectiveSuppressesAndMustCarryAReason(t *testing.T) {
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\n" +
			"//rig:allow noprogramid: the fixture this benchmark measures\n" +
			"var route = \"shelf\"\n",
	})
	wantPass(t, code, out)

	// The same directive with no reason does not match, so it does not excuse.
	code, out = run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\n//rig:allow noprogramid:\nvar route = \"shelf\"\n",
	})
	wantFail(t, code, out, `names the in-house program "shelf"`)
}

func TestAStaleDirectiveIsItselfAFailure(t *testing.T) {
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\n" +
			"//rig:allow noprogramid: nothing here needs excusing\nvar route = \"neutral\"\n",
	})
	wantFail(t, code, out, "the exemption is stale")
}

func TestADirectiveForAnotherAnalyzerDoesNotExcuseThisOne(t *testing.T) {
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\n" +
			"//rig:allow nocontextfree: wrong rule\nvar route = \"shelf\"\n",
	})
	wantFail(t, code, out, `names the in-house program "shelf"`)
}

func TestNoRegistryHandleCatchesAForeignDeclaration(t *testing.T) {
	code, out := run(t, analysis.NoRegistryHandle, map[string]string{
		"internal/kernel/k.go": "package kernel\n\ntype Registry struct{}\n",
		"internal/svc/a.go":    "package svc\n\ntype Registry struct{}\n",
	})
	wantFail(t, code, out, "declares the registry handle Registry")
}

func TestNoRegistryHandleCatchesANamedImport(t *testing.T) {
	code, out := run(t, analysis.NoRegistryHandle, map[string]string{
		"internal/kernel/k.go": "package kernel\n\ntype Registry struct{}\n",
		"internal/svc/a.go": "package svc\n\n" +
			"import k \"github.com/boris-milner/rig/internal/kernel\"\n\n" +
			"func f(r *k.Registry) {}\n",
	})
	wantFail(t, code, out, "names the registry handle from")
}

func TestNoRegistryHandleCatchesAnExportedAccessor(t *testing.T) {
	code, out := run(t, analysis.NoRegistryHandle, map[string]string{
		"internal/kernel/k.go": "package kernel\n\ntype Registry struct{}\n\n" +
			"func Registries() *Registry { return nil }\n",
	})
	wantFail(t, code, out, "returns the registry handle")
}

func TestNoRegistryHandleAllowsAnUnexportedAccessorInsideTheKernel(t *testing.T) {
	code, out := run(t, analysis.NoRegistryHandle, map[string]string{
		"internal/kernel/k.go": "package kernel\n\ntype Registry struct{}\n\n" +
			"func registries() *Registry { return nil }\n",
	})
	wantPass(t, code, out)
}

func TestNoRegistryHandleSaysSoWhenThereIsNoKernel(t *testing.T) {
	code, out := run(t, analysis.NoRegistryHandle, map[string]string{
		"internal/svc/a.go": "package svc\n",
	})
	wantPass(t, code, out)
	if !strings.Contains(out, "cannot fail until it does") {
		t.Fatalf("a vacuous pass has to say it is vacuous, got:\n%s", out)
	}
}

func TestNoEnumZeroCatchesAMeaningfulZero(t *testing.T) {
	code, out := run(t, analysis.NoEnumZero, map[string]string{
		"proto/a.proto": "syntax = \"proto3\";\n\nenum Colour {\n  COLOUR_RED = 0;\n  COLOUR_BLUE = 1;\n}\n",
	})
	wantFail(t, code, out, "has the meaningful zero COLOUR_RED")
	if !strings.Contains(out, "COLOUR_UNSPECIFIED") {
		t.Fatalf("the message has to say what to rename it to, got:\n%s", out)
	}
}

func TestNoEnumZeroCatchesAMissingZero(t *testing.T) {
	code, out := run(t, analysis.NoEnumZero, map[string]string{
		"proto/a.proto": "syntax = \"proto3\";\n\nenum Colour {\n  COLOUR_RED = 1;\n}\n",
	})
	wantFail(t, code, out, "has no zero value")
}

func TestNoEnumZeroAcceptsTheHouseShape(t *testing.T) {
	code, out := run(t, analysis.NoEnumZero, map[string]string{
		"proto/a.proto": "syntax = \"proto3\";\n\nenum Colour {\n" +
			"  COLOUR_UNSPECIFIED = 0;\n  COLOUR_RED = 1;  // a comment\n}\n",
	})
	wantPass(t, code, out)
}

func TestNoEnumZeroIsNotFooledByAComment(t *testing.T) {
	// A commented-out zero must not count as the real one.
	code, out := run(t, analysis.NoEnumZero, map[string]string{
		"proto/a.proto": "syntax = \"proto3\";\n\nenum Colour {\n" +
			"  // COLOUR_UNSPECIFIED = 0;\n  COLOUR_RED = 0;\n}\n",
	})
	wantFail(t, code, out, "has the meaningful zero COLOUR_RED")
}

func TestNoContextFreeCatchesALooseBackground(t *testing.T) {
	code, out := run(t, analysis.NoContextFree, map[string]string{
		"internal/svc/a.go": "package svc\n\nimport \"context\"\n\n" +
			"func f() context.Context { return context.Background() }\n",
	})
	wantFail(t, code, out, "used without a deadline")
}

func TestNoContextFreeAllowsADeadlinedRoot(t *testing.T) {
	code, out := run(t, analysis.NoContextFree, map[string]string{
		"internal/svc/a.go": "package svc\n\nimport (\n\t\"context\"\n\t\"time\"\n)\n\n" +
			"func f() {\n\tctx, cancel := context.WithTimeout(context.Background(), time.Second)\n" +
			"\tdefer cancel()\n\t_ = ctx\n}\n",
	})
	wantPass(t, code, out)
}

func TestNoContextFreeRefusesTODOOutright(t *testing.T) {
	code, out := run(t, analysis.NoContextFree, map[string]string{
		"internal/svc/a.go": "package svc\n\nimport (\n\t\"context\"\n\t\"time\"\n)\n\n" +
			"func f() {\n\tctx, cancel := context.WithTimeout(context.TODO(), time.Second)\n" +
			"\tdefer cancel()\n\t_ = ctx\n}\n",
	})
	wantFail(t, code, out, "has not been decided")
}

func TestNoContextFreeWantsTheContextFirst(t *testing.T) {
	code, out := run(t, analysis.NoContextFree, map[string]string{
		"internal/svc/a.go": "package svc\n\nimport \"context\"\n\n" +
			"func f(name string, ctx context.Context) {}\n",
	})
	wantFail(t, code, out, "at argument 2")
}

func TestNoContextFreeWantsItCalledCtx(t *testing.T) {
	code, out := run(t, analysis.NoContextFree, map[string]string{
		"internal/svc/a.go": "package svc\n\nimport \"context\"\n\n" +
			"func f(c context.Context) {}\n",
	})
	wantFail(t, code, out, `names its context "c"`)
}

func TestNoContextFreeMakesWithCancelCostAReason(t *testing.T) {
	src := "package svc\n\nimport \"context\"\n\n" +
		"func f(ctx context.Context) {\n\tc, cancel := context.WithCancel(ctx)\n" +
		"\tdefer cancel()\n\t_ = c\n}\n"
	code, out := run(t, analysis.NoContextFree, map[string]string{"internal/svc/a.go": src})
	wantFail(t, code, out, "no deadline of its own")

	excused := strings.Replace(src, "\tc, cancel :=",
		"\t//rig:allow nocontextfree: the daemon's lifetime, not a call\n\tc, cancel :=", 1)
	code, out = run(t, analysis.NoContextFree, map[string]string{"internal/svc/a.go": excused})
	wantPass(t, code, out)
}

func TestDirectiveTextInsideAStringIsNotADirective(t *testing.T) {
	// The bug this catches was found by running the analyzers over their own
	// tests: every fixture above holds directive text inside a string
	// literal, and a raw line scan read all of them as live exemptions.
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a.go": "package svc\n\n" +
			"var fixture = \"//rig:allow noprogramid: not a real directive\"\n" +
			"var route = \"shelf\"\n",
	})
	wantFail(t, code, out, `names the in-house program "shelf"`)
	if strings.Contains(out, "stale") {
		t.Fatalf("a directive inside a string is not an exemption, got:\n%s", out)
	}
}

func TestADirectiveInASkippedFileIsNotCalledStale(t *testing.T) {
	code, out := run(t, analysis.NoProgramID, map[string]string{
		"internal/svc/a_test.go": "package svc\n\n" +
			"//rig:allow noprogramid: the pilot runs the real binary\nvar pilot = \"shelf\"\n",
	})
	wantPass(t, code, out)
}
